import { z } from 'zod';
const text = z.string().trim().min(1).max(2000);
const id = z.string().regex(/^[a-z][a-z0-9_-]{0,59}$/);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s => !Number.isNaN(Date.parse(s)) && new Date(s).toISOString().slice(0,10) === s, 'Use a valid date');
const confidence = z.enum(['HIGH','MEDIUM','LOW']);
const classification = z.enum(['VERIFIED','OBSERVED','CALCULATED','MODELLED','HYPOTHESIS']);
const count = z.number().int().nonnegative().max(10000000).nullable();
const amount = z.number().nonnegative().max(1000000000).nullable();
export const fields = ['revenue','completed','enquiries','bookings','availableHours','bookedHours','eligibleClients','rebookedClients','searchViews','searchActions'] as const;
export const monthSchema = z.strictObject({month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),revenue:amount,completed:count,enquiries:count,bookings:count,availableHours:amount,bookedHours:amount,eligibleClients:count,rebookedClients:count,searchViews:count,searchActions:count,evidenceIds:z.array(id).min(1).max(30)}).superRefine((m,c)=>{for(const [a,b] of [['bookings','enquiries'],['bookedHours','availableHours'],['rebookedClients','eligibleClients'],['searchActions','searchViews']] as const) if(m[a]!==null&&m[b]!==null&&m[a]!>m[b]!) c.addIssue({code:'custom',path:[a],message:`Must not exceed ${b}`});});
export const evidenceSchema=z.strictObject({id,title:text,source:text,observedAt:date,summary:text,classification,confidence,limitations:z.string().max(2000)});
export const findingSchema=z.strictObject({id,category:z.enum(['commercial','demand','conversion','capacity','retention','pricing','competition']),title:text,answer:text,diagnosis:text,alternative:text,materiality:z.enum(['critical','high','medium','low']),evidenceIds:z.array(id).min(1).max(30)});
export const recommendationSchema=z.strictObject({id,findingId:id,title:text,action:text,owner:text,targetMetric:z.enum(['revenue','averageValue','conversion','utilisation','rebooking','searchActionRate','revenuePerHour']),phase:z.enum(['1–30','31–60','61–90']),confidence,impact:z.number().int().min(1).max(5),urgency:z.number().int().min(1).max(3),effort:z.number().int().min(1).max(5),assumptions:text});
export const inputSchema=z.strictObject({schemaVersion:z.literal('studio-intelligence/1.0'),studio:z.strictObject({name:z.string().trim().min(2).max(120),location:z.string().trim().min(2).max(120)}),representative:z.boolean(),period:z.strictObject({start:date,end:date}),currency:z.literal('GBP'),targets:z.strictObject({conversion:z.number().gt(0).max(100),utilisation:z.number().gt(0).max(100),rebooking:z.number().gt(0).max(100),rationale:text}),months:z.array(monthSchema).min(1).max(24),evidence:z.array(evidenceSchema).min(1).max(100),findings:z.array(findingSchema).min(1).max(30),recommendations:z.array(recommendationSchema).min(1).max(30),competitors:z.array(z.strictObject({name:text,observation:text,evidenceId:id})).max(20),limitations:z.array(text).min(1).max(30)}).superRefine((r,c)=>{
const issue=(message:string)=>c.addIssue({code:'custom',message});
if(r.period.start>r.period.end) issue('Period end must follow start');
const first=r.period.start.slice(0,7),last=r.period.end.slice(0,7);
if(r.period.start.slice(8)!=='01'||new Date(Date.parse(r.period.end)+86400000).getUTCDate()!==1) issue('Use complete calendar months for comparable aggregates');
const expected=[];for(let d=new Date(`${first}-01T00:00:00Z`);d.toISOString().slice(0,7)<=last&&expected.length<25;d.setUTCMonth(d.getUTCMonth()+1))expected.push(d.toISOString().slice(0,7));
if(JSON.stringify(r.months.map(m=>m.month))!==JSON.stringify(expected))issue('Include every month in order; use null for unavailable measurements');
for(const list of [r.evidence,r.findings,r.recommendations])if(new Set(list.map(x=>x.id)).size!==list.length)issue('IDs must be unique within each collection');
const evidence=new Map(r.evidence.map(e=>[e.id,e]));
for(const refs of [...r.months.map(m=>m.evidenceIds),...r.findings.map(f=>f.evidenceIds),r.competitors.map(c=>[c.evidenceId]).flat()])for(const ref of refs)if(!evidence.has(ref))issue(`Missing evidence: ${ref}`);
for(const rec of r.recommendations){const f=r.findings.find(f=>f.id===rec.findingId);if(!f)issue(`Missing finding: ${rec.findingId}`);else {const ranks={LOW:0,MEDIUM:1,HIGH:2};const lowest=Math.min(...f.evidenceIds.map(e=>ranks[evidence.get(e)?.confidence??'LOW']));if(ranks[rec.confidence]>lowest)issue(`Recommendation ${rec.id} confidence exceeds its evidence`);}}
});
export type Input=z.infer<typeof inputSchema>;
export type Metric={key:string;label:string;value:number|null;unit:string;formula:string;reason:string|null;confidence:'HIGH'|'MEDIUM'|'LOW';evidenceIds:string[]};
export type Manifest={schemaVersion:'studio-intelligence/1.0';calculationVersion:'1.0.0';generatedAt:string;input:Input;metrics:Metric[];score:number|null;scoreCoverage:number;opportunities:Array<Input['recommendations'][number]&{rank:number}>};
export const factor={HIGH:1,MEDIUM:.65,LOW:.35};
export function generateReport(raw:unknown,now=new Date().toISOString()):Manifest{
const input=inputSchema.parse(raw);const evidenceIds=[...new Set(input.months.flatMap(m=>m.evidenceIds))];const levels=['LOW','MEDIUM','HIGH'] as const;const confidence=levels[Math.min(...evidenceIds.map(id=>levels.indexOf(input.evidence.find(e=>e.id===id)!.confidence)))];
const sum=(key:typeof fields[number])=>input.months.some(m=>m[key]===null)?null:input.months.reduce((t,m)=>t+(m[key]??0),0);
const ratio=(a:number|null,b:number|null,mult=1)=>a===null||b===null||b===0?null:a/b*mult;
const metric=(key:string,label:string,value:number|null,unit:string,formula:string):Metric=>({key,label,value,unit,formula,reason:value===null?'Missing observations or a zero denominator; collect the source data before drawing a conclusion.':null,confidence,evidenceIds});
const metrics=[metric('revenue','Net studio revenue',sum('revenue'),'GBP','Sum revenue after refunds'),metric('completed','Completed appointments',sum('completed'),'count','Sum completed appointments'),metric('averageValue','Average appointment value',ratio(sum('revenue'),sum('completed')),'GBP','Revenue ÷ completed appointments'),metric('conversion','Enquiry conversion',ratio(sum('bookings'),sum('enquiries'),100),'%','Confirmed cohort bookings ÷ enquiries × 100'),metric('utilisation','Artist utilisation',ratio(sum('bookedHours'),sum('availableHours'),100),'%','Booked hours ÷ available artist hours × 100'),metric('rebooking','Rebooking rate',ratio(sum('rebookedClients'),sum('eligibleClients'),100),'%','Rebooked eligible clients ÷ eligible clients × 100'),metric('searchActionRate','Search action rate',ratio(sum('searchActions'),sum('searchViews'),100),'%','Tracked actions ÷ search views × 100'),metric('revenuePerHour','Revenue / available hour',ratio(sum('revenue'),sum('availableHours')),'GBP','Revenue ÷ available artist hours')];
const dimensions=(['conversion','utilisation','rebooking'] as const).map(key=>{const v=metrics.find(m=>m.key===key)!.value;return v===null?null:Math.min(100,v/input.targets[key]*100)});const scoreCoverage=dimensions.filter(v=>v!==null).length;
return {schemaVersion:'studio-intelligence/1.0',calculationVersion:'1.0.0',generatedAt:now,input,metrics,score:scoreCoverage===3?Math.round(dimensions.reduce<number>((a,b)=>a+(b??0),0)/3):null,scoreCoverage,opportunities:input.recommendations.map(r=>({...r,rank:Math.round(r.impact*factor[r.confidence]*r.urgency/r.effort*100)/100})).sort((a,b)=>b.rank-a.rank||a.id.localeCompare(b.id))};
}
export function readManifest(value:unknown):Manifest{const v=value as Manifest;if(v?.schemaVersion!=='studio-intelligence/1.0'||v.calculationVersion!=='1.0.0'||typeof v.generatedAt!=='string')throw new Error('Unsupported report version');return generateReport(v.input,v.generatedAt);}
export function format(value:number|null,unit='count'){return value===null?'Not measured':unit==='GBP'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(value):`${new Intl.NumberFormat('en-GB',{maximumFractionDigits:1}).format(value)}${unit==='%'?'%':''}`;}
