import { generateReport, type Input } from './contract';
export const goldenInput:Input={schemaVersion:'studio-intelligence/1.0',studio:{name:'Northline Tattoo',location:'Manchester · UK'},representative:true,period:{start:'2026-07-01',end:'2026-09-30'},currency:'GBP',targets:{conversion:60,utilisation:75,rebooking:40,rationale:'Illustrative planning targets agreed for this fictional example. These are not industry benchmarks.'},months:[
{month:'2026-07',revenue:21840,completed:112,enquiries:160,bookings:72,availableHours:480,bookedHours:294,eligibleClients:100,rebookedClients:24,searchViews:8400,searchActions:420,evidenceIds:['ledger','enquiry-log','diary','search']},
{month:'2026-08',revenue:24120,completed:120,enquiries:172,bookings:86,availableHours:480,bookedHours:318,eligibleClients:108,rebookedClients:30,searchViews:9200,searchActions:478,evidenceIds:['ledger','enquiry-log','diary','search']},
{month:'2026-09',revenue:26760,completed:132,enquiries:184,bookings:101,availableHours:480,bookedHours:348,eligibleClients:120,rebookedClients:38,searchViews:10100,searchActions:565,evidenceIds:['ledger','enquiry-log','diary','search']}],
evidence:[
{id:'ledger',title:'Appointment revenue ledger',source:'Fictional aggregated ledger · July–September 2026',observedAt:'2026-09-30',summary:'£72,720 revenue after refunds across 364 completed appointments.',classification:'MODELLED',confidence:'MEDIUM',limitations:'Representative numbers only. Not a real studio, bank reconciliation or case study.'},
{id:'enquiry-log',title:'Enquiry cohort log',source:'Fictional enquiry cohorts · July–September 2026',observedAt:'2026-09-30',summary:'516 enquiries produced 259 confirmed bookings. Cohorts use a consistent booking observation window.',classification:'MODELLED',confidence:'MEDIUM',limitations:'No causal evidence that response speed caused lost bookings. Unbooked enquiries may include unsuitable requests.'},
{id:'diary',title:'Artist diary and rebooking review',source:'Fictional availability and next-booking summary',observedAt:'2026-09-30',summary:'960 booked hours of 1,440 available; 92 next bookings among 328 eligible clients.',classification:'MODELLED',confidence:'MEDIUM',limitations:'Available hours exclude planned time off. Rebooking is not lifetime retention.'},
{id:'search',title:'Local search activity',source:'Fictional business-profile export',observedAt:'2026-09-30',summary:'27,700 search views and 1,463 tracked actions.',classification:'MODELLED',confidence:'MEDIUM',limitations:'Actions may repeat and cannot be equated to enquiries or attributed revenue.'},
{id:'competitor-review',title:'Local competitor journey review',source:'Fictional comparison of two studio enquiry journeys',observedAt:'2026-09-29',summary:'One fictional comparator exposes appointment information before the enquiry form.',classification:'HYPOTHESIS',confidence:'LOW',limitations:'Illustrates the review format only; no actual competitor or market benchmark.'}],
findings:[
{id:'follow-up',category:'conversion',title:'Convert the demand already arriving.',answer:'Half of recorded enquiries became bookings. A consistent follow-up process is the first intervention to test.',diagnosis:'The enquiry-to-booking handover may leave suitable clients without a clear next step. Confirm this by reviewing unbooked enquiries before changing the process.',alternative:'Artist fit, budget and availability may explain a material share of unbooked enquiries.',materiality:'high',evidenceIds:['enquiry-log']},
{id:'rebooking',category:'retention',title:'Make the next appointment an intentional conversation.',answer:'28% of eligible clients have a next booking. Introduce a relevant rebooking prompt and measure the result.',diagnosis:'A next-session conversation may be inconsistent across artists. Focus first on clients whose work naturally needs another session.',alternative:'Single-session tattoos and client preference mean not every eligible client should rebook.',materiality:'medium',evidenceIds:['diary']},
{id:'capacity',category:'capacity',title:'Use the diary before adding more spend.',answer:'Artist utilisation is 67% over the quarter, leaving recorded capacity to absorb better-qualified bookings.',diagnosis:'Match follow-up invitations to genuine artist availability, style and session length.',alternative:'Aggregate availability can hide peak-day shortages and less popular times.',materiality:'medium',evidenceIds:['diary','ledger']}],
recommendations:[
{id:'rec-follow-up',findingId:'follow-up',title:'Test a consistent enquiry follow-up',action:'Review 20 unbooked enquiries. Set one owner and a two-step follow-up process for suitable enquiries, with consent respected. Compare the next 30-day cohort with the baseline.',owner:'Studio manager',targetMetric:'conversion',phase:'1–30',confidence:'MEDIUM',impact:5,urgency:3,effort:2,assumptions:'Only suitable enquiries enter the test. Track booking conversion and reasons for not booking; no guaranteed revenue increase.'},
{id:'rec-rebooking',findingId:'rebooking',title:'Offer the right next session',action:'Agree an end-of-session prompt for work that needs a follow-up. Record eligible clients and next bookings consistently for four weeks.',owner:'Lead artist',targetMetric:'rebooking',phase:'31–60',confidence:'MEDIUM',impact:4,urgency:2,effort:2,assumptions:'A relevant follow-up benefits the client; avoid pushing appointments that are not needed.'},
{id:'rec-capacity',findingId:'capacity',title:'Match demand to available artist time',action:'Review diary gaps by artist, day and style. Offer suitable open slots to opted-in enquiries. Review results at day 90 before buying more traffic.',owner:'Studio manager + INKSIGHTS',targetMetric:'utilisation',phase:'61–90',confidence:'MEDIUM',impact:4,urgency:2,effort:3,assumptions:'Reported hours are genuinely bookable. Compare appointment mix and seasonality before claiming attribution.'}],
competitors:[{name:'Comparator A · fictional',observation:'Clear session guidance before enquiry. Test whether equivalent guidance reduces unsuitable enquiries.',evidenceId:'competitor-review'}],limitations:['All data is fictional and illustrates the product; this is not a client result or case study.','Targets are planning assumptions, not validated tattoo-industry benchmarks.','This report measures rebooking, not lifetime retention. Net revenue is not profit.','Observed changes do not establish that an intervention caused the outcome.']};
export const golden=generateReport(goldenInput,'2026-10-07T12:00:00.000Z');
