import PDFDocument from 'pdfkit';import sharp from 'sharp';import path from 'node:path';import {format,factor,type Manifest} from './contract';import type {Progress} from '@/components/report';
export async function makePdf(report:Manifest,version:number,status:string,progress:Progress[]=[]):Promise<Buffer>{
const doc=new PDFDocument({size:'A4',margins:{top:70,bottom:65,left:48,right:48},bufferPages:true,info:{Title:`${report.input.studio.name} — Studio Intelligence v${version}`,Author:'INKSIGHTS',Subject:report.input.representative?'Fictional representative report':'Confidential studio intelligence'}});
const chunks:Buffer[]=[];const done=new Promise<Buffer>((resolve,reject)=>{doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)});
const fonts=path.join(process.cwd(),'public/fonts');doc.registerFont('Body',path.join(fonts,'Poppins-Regular.ttf'));doc.registerFont('Bold',path.join(fonts,'Poppins-SemiBold.ttf'));
const logo=await sharp(path.join(process.cwd(),'public/brand/logo-v3/primary-light.svg')).resize({width:600}).png().toBuffer();
const width=499;const title=(s:string)=>{if(doc.y>665)doc.addPage();doc.moveDown(.8);doc.font('Bold').fontSize(21).fillColor('#0A0F14').text(s,{width});doc.moveDown(.35)};
const sub=(s:string)=>{if(doc.y>700)doc.addPage();doc.font('Bold').fontSize(12).fillColor('#00665F').text(s,{width});doc.moveDown(.35)};
const p=(s:string,small=false)=>{doc.font('Body').fontSize(small?8:10).fillColor(small?'#475569':'#1F2937').text(s,{width,lineGap:4});doc.moveDown(.65)};
const page=()=>{doc.addPage()};
const m=(k:string)=>report.metrics.find(m=>m.key===k)!;const metric=(key:string)=>{const v=m(key);sub(`${v.label}: ${format(v.value,v.unit)}`);p(`${v.formula} · ${v.confidence} confidence. Evidence: ${v.evidenceIds.join(', ')}. ${v.reason||''}`,true)};
const total=(k:keyof Manifest['input']['months'][number])=>report.input.months.some(m=>m[k]===null)?'Not measured':format(report.input.months.reduce((n,m)=>n+Number(m[k]),0));
const header=()=>{doc.image(logo,48,25,{width:130});doc.moveTo(48,58).lineTo(547,58).strokeColor('#D4DEE3').stroke();doc.x=48;doc.y=77};doc.on('pageAdded',header);header();
const {input}=report;p(`STUDIO INTELLIGENCE / ${input.representative?'FICTIONAL REFERENCE':status.toUpperCase()}`,true);doc.font('Bold').fontSize(31).fillColor('#0A0F14').text(input.studio.name,{width});p(`${input.studio.location} · ${input.period.start} — ${input.period.end} · Version ${version}`);title('01 / Executive Intelligence');sub(input.findings[0].title);p(input.findings[0].answer);for(const key of ['revenue','conversion','utilisation','rebooking'])metric(key);p(input.representative?'All values are fictional. This is not a real client result or case study.':input.limitations[0],true);
page();title('02 / Studio Intelligence Score');sub(report.score===null?'Insufficient evidence':`${report.score} / 100 — diagnostic planning index`);for(const k of ['conversion','utilisation','rebooking'] as const)p(`${m(k).label}: ${format(m(k).value,'%')} against ${input.targets[k]}% target.`,true);p(input.targets.rationale);p(`Coverage: ${report.scoreCoverage}/3. Equal weights. Each dimension = min(100, actual ÷ target × 100). The overall index requires all three dimensions. It is not an industry benchmark or statistical probability.`,true);title('03 / Commercial Performance');for(const month of input.months)p(`${month.month} — Revenue ${format(month.revenue,'GBP')} · Appointments ${format(month.completed)} · Enquiries ${format(month.enquiries)} · Confirmed bookings ${format(month.bookings)}`);p('Revenue is after refunds and before operating costs. No profit or causal growth claim is implied.',true);
page();title('04 / Demand / Visibility');p(`Search views: ${total('searchViews')}. Tracked actions: ${total('searchActions')}.`);metric('searchActionRate');p('Actions may repeat and cannot be equated to unique leads or revenue.',true);title('05 / Enquiry & Booking Funnel');p(`Enquiries: ${total('enquiries')} → confirmed cohort bookings: ${total('bookings')}.`);metric('conversion');title('06 / Capacity / Utilisation');p(`Booked artist hours: ${total('bookedHours')}. Available artist hours: ${total('availableHours')}.`);metric('utilisation');p('Available hours exclude planned time off. Aggregate figures can hide differences by artist and day.',true);
page();title('07 / Retention / Rebooking');p(`Eligible clients: ${total('eligibleClients')}. Clients with a next booking: ${total('rebookedClients')}.`);metric('rebooking');p('Rebooking is not lifetime retention or lifetime client value.',true);title('08 / Pricing / Revenue');metric('averageValue');metric('revenuePerHour');p('Appointment mix, duration and specialism affect these averages. They alone do not justify a price change.',true);title('09 / Competitive Position');if(!input.competitors.length)p('Not assessed. No dated comparable competitor evidence supplied.');for(const c of input.competitors){sub(c.name);p(c.observation);p(`Evidence: ${c.evidenceId}`,true)}
page();title('10 / Findings');for(const f of input.findings){sub(f.title);p(f.answer);p(`Diagnosis: ${f.diagnosis}`);p(`Alternative: ${f.alternative}`);p(`${f.materiality.toUpperCase()} priority · ${f.category} · Evidence: ${f.evidenceIds.join(', ')}`,true)}
page();title('11 / Opportunities');for(const [i,r] of report.opportunities.entries()){sub(`${i+1}. ${r.title}`);p(`Priority score ${r.rank}: impact ${r.impact} × confidence ${factor[r.confidence]} × urgency ${r.urgency} ÷ effort ${r.effort}.`,true);p(r.assumptions)}title('12 / Recommendations');for(const r of report.opportunities){sub(r.title);p(r.action);p(`Owner: ${r.owner} · Measure: ${m(r.targetMetric).label} · ${r.confidence} confidence · Finding: ${r.findingId}`,true)}
page();title('13 / 90-Day Plan');for(const phase of ['1–30','31–60','61–90']){sub(`Days ${phase}`);for(const r of input.recommendations.filter(r=>r.phase===phase)){p(`${r.title} — ${r.owner}`);const pr=progress.find(p=>p.recommendation_id===r.id);p(`Status: ${pr?.status?.replaceAll('_',' ')||'Not started'}`,true);if(pr){p(`Progress updated ${pr.updated_at}`,true);for(const k of ['intervention','outcome','attribution','learning'] as const)if(pr[k])p(`${k}: ${pr[k]}`,true)}}}p('Progress notes are separate dated records. They do not change the approved report. Observed improvement alone is not proof of causation.',true);
page();title('14 / Evidence');for(const e of input.evidence){sub(`${e.id} / ${e.title}`);p(e.summary);p(`${e.classification} · ${e.confidence} confidence · Observed ${e.observedAt}`,true);p(`Source: ${e.source}`,true);p(`Limit: ${e.limitations||'No additional limitations recorded.'}`,true)}
page();title('15 / Methodology');p('Observation → Normalised Data → Metric → Evidence → Finding → Diagnosis → Opportunity → Recommendation → Intervention → Outcome → Attribution → Learning.');p('Input is validated for dates, cohorts, subsets, missing values and evidence references. Calculations are deterministic. Findings and diagnoses remain analyst judgements. Missing components and zero denominators produce no measurement; they are never substituted with zero.');for(const metric of report.metrics)p(`${metric.label}: ${metric.formula}.`,true);p('Confidence is the lowest supporting metric evidence level. Targets are explicit planning assumptions. Opportunity rankings prioritise tests and do not promise money.');sub('Limitations');input.limitations.forEach(l=>p(l));p(`Schema: ${report.schemaVersion} · Calculation: ${report.calculationVersion} · Generated ${report.generatedAt}. This PDF is a secondary export of the interactive report.`,true);
const range=doc.bufferedPageRange();for(let i=range.start;i<range.start+range.count;i++){doc.switchToPage(i);const bottom=doc.page.margins.bottom;doc.page.margins.bottom=0;doc.font('Body').fontSize(7).fillColor('#475569').text(`INKSIGHTS  /  ${input.representative?'FICTIONAL REFERENCE':'CONFIDENTIAL'}  /  v${version}`,48,808,{lineBreak:false});doc.text(`${i+1} / ${range.count}`,480,808,{lineBreak:false,width:67,align:'right'});doc.page.margins.bottom=bottom}
doc.end();return done;
}
