import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Database, Eye, ShieldCheck, Workflow } from "lucide-react";
import { CtaSection, JsonLd, PageHero, PublicShell, SectionHeading } from "@/components/public-site";

const CANONICAL_URL = "https://getinksights.co.uk/about";
export const Route = createFileRoute("/about")({ component: AboutPage, head: () => ({ meta: [{ title: "About INKSIGHTS | Tattoo Studio Intelligence" }, { name: "description", content: "INKSIGHTS builds evidence-led growth and intelligence systems around the economics of running a UK tattoo studio." }, { property: "og:title", content: "About INKSIGHTS | Tattoo Studio Intelligence" }, { property: "og:url", content: CANONICAL_URL }], links: [{ rel: "canonical", href: CANONICAL_URL }] }) });
const principles = [{ icon: Eye, title: "Evidence before theatre", description: "Demonstrations are labelled, unknowns stay unknown and client outcomes are never invented to make an early-stage business appear larger." }, { icon: Workflow, title: "Workflow before software", description: "A new platform cannot repair unclear ownership, weak policies or an undefined booking journey. Diagnose the process first." }, { icon: ShieldCheck, title: "Automation with boundaries", description: "Automations need consent, human escalation, validation and a way to stop. Exceptions are part of the design." }, { icon: CheckCircle2, title: "Smallest useful intervention", description: "A studio with one visibility problem should not be sold a large ongoing engagement. Scope expands only when evidence and capacity justify it." }] as const;
function AboutPage() { return <PublicShell><JsonLd data={{ "@context": "https://schema.org", "@type": "AboutPage", name: "About INKSIGHTS", url: CANONICAL_URL, mainEntity: { "@type": "Organization", name: "INKSIGHTS", url: "https://getinksights.co.uk/", description: "Growth intelligence for UK tattoo studios, built from direct tattoo-industry experience." } }} />
  <PageHero eyebrow="Built from inside tattooing" title={<>The economics of a tattoo studio are different.</>} description={<>INKSIGHTS was built around the operating reality of custom tattooing: portfolios create trust, enquiries require qualification, deposits protect time, artists have different capacity and specialisms, and the client relationship can span months or years.</>}><a href="/studio-growth-check" className="inline-flex min-h-12 items-center justify-center rounded-full bg-mint px-6 py-3 font-bold text-ink-deep hover:bg-mint-soft">Run the free Studio Audit →</a></PageHero>
  <section><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-2 lg:items-center md:py-28"><div><SectionHeading eyebrow="Founder context" title="Direct operating experience, then data." description="INKSIGHTS was started by a working black-and-grey realism tattoo artist. The niche was not selected from a marketing list; the product is being built around problems observed from inside tattooing." /><div className="mt-7 space-y-4 text-base leading-relaxed text-muted-foreground"><p>That experience is a starting advantage, not proof that every recommendation is correct. INKSIGHTS combines industry context with structured evidence, explicit assumptions and measurable outcomes.</p><p>The objective is to build a proprietary intelligence layer around the conditions that influence studio performance — then improve the models as real studio data accumulates.</p></div></div><div className="rounded-3xl border border-mint/35 bg-ink p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-mint">The asset being built</p><ul className="mt-6 space-y-4 text-sm leading-relaxed text-muted-foreground"><li className="rounded-xl border border-border bg-ink-deep p-4"><strong className="text-ice">Studio economics:</strong> clients, booking value, frequency, utilisation and leakage.</li><li className="rounded-xl border border-border bg-ink-deep p-4"><strong className="text-ice">Market intelligence:</strong> local demand, visibility, competitors and commercial search opportunities.</li><li className="rounded-xl border border-border bg-ink-deep p-4"><strong className="text-ice">Operating intelligence:</strong> enquiry, booking, cancellation, retention and exception signals.</li><li className="rounded-xl border border-border bg-ink-deep p-4"><strong className="text-ice">Proprietary models:</strong> scoring, opportunity detection, recommendations and benchmarks that improve with evidence.</li></ul></div></div></section>
  <section className="border-y border-border bg-ink"><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><SectionHeading eyebrow="Operating principles" title="How trust is earned." /><div className="mt-10 grid gap-5 md:grid-cols-2">{principles.map(({ icon: Icon, title, description }) => <div key={title} className="rounded-2xl border border-border bg-ink-deep p-7"><Icon className="h-7 w-7 text-mint" /><h2 className="mt-5 font-display text-2xl font-black text-ice">{title}</h2><p className="mt-3 leading-relaxed text-muted-foreground">{description}</p></div>)}</div></div></section>
  <section><div className="mx-auto max-w-5xl px-6 py-20 text-center md:py-28"><Database className="mx-auto h-8 w-8 text-mint" /><h2 className="mt-5 font-display text-4xl font-black text-ice md:text-6xl">Built to turn every audit into better intelligence.</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-muted-foreground">Every studio interaction should improve three things: the customer's decision, the studio's operating baseline and the quality of INKSIGHTS' underlying dataset. That is the long-term moat.</p><a href="/case-studies" className="mt-8 inline-flex rounded-full border border-mint px-6 py-3 font-bold text-mint hover:bg-mint/10">See the proof standard</a></div></section>
  <CtaSection />
</PublicShell>; }
