import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Database, GitPullRequest, ShieldCheck, Workflow } from "lucide-react";
import { CtaSection, JsonLd, PageHero, PublicShell, SectionHeading } from "@/components/public-site";

const CANONICAL_URL = "https://getinksights.co.uk/case-studies";
export const Route = createFileRoute("/case-studies")({ component: ProofPage, head: () => ({ meta: [{ title: "INKSIGHTS Proof | Working Systems, Methodology & Results" }, { name: "description", content: "Inspect the evidence behind INKSIGHTS: working systems, methodology, demonstrations and the standard for verified tattoo studio results." }, { property: "og:title", content: "INKSIGHTS Proof" }, { property: "og:url", content: CANONICAL_URL }], links: [{ rel: "canonical", href: CANONICAL_URL }] }) });
const proofTypes = [{ icon: Database, title: "Working product", text: "Real infrastructure, diagnostics, data models and workflows that can be inspected rather than described abstractly." }, { icon: Workflow, title: "Methodology", text: "Clear definitions, evidence boundaries, calculations and decision rules showing how INKSIGHTS moves from signal to recommendation." }, { icon: GitPullRequest, title: "Build history", text: "Version-controlled implementation, validation and controlled releases provide an auditable development trail." }, { icon: ShieldCheck, title: "Verified results", text: "Client outcomes will be published only when the baseline, intervention, measurement window and attribution can be evidenced." }];
function ProofPage() { return <PublicShell><JsonLd data={{ "@context": "https://schema.org", "@type": "CollectionPage", name: "INKSIGHTS Proof", url: CANONICAL_URL, description: "Working systems, methodology, demonstrations and verified outcomes." }} />
  <PageHero eyebrow="Proof, not performance theatre" title={<>See what is real, what is modelled and what still needs to be proven.</>} description={<>INKSIGHTS is early-stage. The proof library therefore separates working infrastructure and methodology from simulated demonstrations and future client outcomes. That standard gets stricter, not looser, as the business grows.</>}><a href="/studio-growth-check" className="inline-flex min-h-12 items-center justify-center rounded-full bg-mint px-6 py-3 font-bold text-ink-deep hover:bg-mint-soft">Test the product yourself →</a></PageHero>
  <section className="border-b border-border bg-ink"><div className="mx-auto max-w-7xl px-6 py-10"><div className="rounded-2xl border border-amber-300/35 bg-amber-300/10 p-5 text-sm leading-relaxed text-amber-100"><strong className="text-amber-200">Current proof status:</strong> there are no fabricated paying-client performance claims on this page. Demonstration figures are labelled as demonstrations, and modelled opportunity estimates are not presented as confirmed revenue.</div></div></section>
  <section><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><SectionHeading eyebrow="Four proof layers" title="A commercial claim should always have a corresponding evidence type." /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{proofTypes.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-border bg-ink p-6"><Icon className="h-7 w-7 text-mint" /><h2 className="mt-5 font-display text-xl font-black text-ice">{title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div></div></section>
  <section className="border-y border-border bg-ink"><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><SectionHeading eyebrow="Demonstration" title="What the diagnostic looks like when the evidence points to conversion." description="This example is simulated. It exists to demonstrate the decision format, not to imply a client result." /><div className="mt-10 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-border bg-ink-deep p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-mint">Simulated studio</p><ul className="mt-6 space-y-3 text-sm leading-relaxed text-muted-foreground"><li>Multi-artist UK studio</li><li>Strong portfolio and credible reviews</li><li>Traffic reaches profile and website</li><li>Booking route is split across several actions</li><li>No clear response-time expectation</li></ul></div><div className="rounded-3xl border border-mint/30 bg-ink-deep p-7"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Visibility", "64"], ["Trust", "78"], ["Conversion", "36"], ["Readiness", "85"]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-ink p-4"><div className="font-display text-3xl font-black text-mint">{value}</div><div className="mt-1 text-xs text-muted-foreground">{label}</div></div>)}</div><div className="mt-5 rounded-xl border border-border bg-ink p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-muted-foreground">Primary diagnosis</p><h2 className="mt-2 font-display text-2xl font-black text-ice">Visible enough to lose enquiries.</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">The example routes the owner toward conversion clarity rather than more traffic. That is the point of the intelligence layer: choose the constraint before choosing the tactic.</p></div></div></div></div></section>
  <section><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><SectionHeading eyebrow="Future client case-study standard" title="Results become proof only when they survive scrutiny." /><div className="mt-10 grid gap-5 md:grid-cols-2">{["Client permission and studio context", "Starting baseline and data limitations", "Exact intervention and implementation period", "Relevant external factors such as seasonality or ad spend", "A sensible outcome window", "Commercial metrics plus limitations and unsuccessful elements"].map((item) => <div key={item} className="flex gap-3 rounded-xl border border-border bg-ink p-5 text-sm leading-relaxed text-muted-foreground"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-mint" />{item}</div>)}</div></div></section>
  <CtaSection title="Become part of the first verified INKSIGHTS results set." description="Founding studios can help turn the current methodology into measured, permissioned evidence." />
</PublicShell>; }
