import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { CtaSection, JsonLd, PageHero, PrimaryButton, PublicShell, SectionHeading } from "@/components/public-site";
import { publicOffers } from "@/lib/offer-data";

const CANONICAL_URL = "https://getinksights.co.uk/offers";
export const Route = createFileRoute("/offers")({ component: OffersPage, head: () => ({ meta: [{ title: "Tattoo Studio Growth Services UK | INKSIGHTS" }, { name: "description", content: "Choose the smallest useful intervention for your UK tattoo studio: visibility, revenue, booking or ongoing intelligence." }, { property: "og:title", content: "Tattoo Studio Growth Services UK | INKSIGHTS" }, { property: "og:url", content: CANONICAL_URL }], links: [{ rel: "canonical", href: CANONICAL_URL }] }) });

const routes = [
  ["Not enough enquiries?", "Visibility", "Measure local search demand, competitive visibility and the pages or profiles that may be suppressing discovery.", "/offers/72-hour-visibility-fix"],
  ["Enquiries but too few bookings?", "Conversion", "Diagnose qualification, response, booking, deposit and client-journey friction before buying more traffic.", "/offers/booking-retention-engine"],
  ["Artists have empty time?", "Revenue", "Separate demand from utilisation, pricing, scheduling and repeat-client constraints.", "/offers/revenue-audit"],
  ["You cannot tell what is changing?", "Intelligence", "Establish a baseline and monitor the public and commercial signals that deserve an owner's attention.", "/offers/visibility-watch"],
];

function OffersPage() {
  return <PublicShell><JsonLd data={{ "@context": "https://schema.org", "@type": "CollectionPage", name: "INKSIGHTS tattoo studio growth services", url: CANONICAL_URL }} />
    <PageHero eyebrow="Solutions by constraint" title={<>Do not buy a larger service than the studio needs.</>} description={<>INKSIGHTS starts with the problem. We diagnose the constraint, define what can actually be measured and then use the smallest practical intervention that can remove it.</>}><PrimaryButton href="/studio-growth-check">Diagnose the studio first</PrimaryButton></PageHero>
    <section className="bg-ink"><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><SectionHeading eyebrow="Start with the symptom" title="What is holding the studio back?" description="Choose the closest match. The route is deliberately diagnostic: if another intervention is more appropriate, we will say so." /><div className="mt-10 grid gap-5 md:grid-cols-2">{routes.map(([problem, outcome, text, href]) => <a key={problem} href={href} className="group rounded-3xl border border-border bg-ink-deep p-7 transition hover:border-mint"><p className="text-xs font-bold uppercase tracking-[.16em] text-mint">{outcome}</p><h2 className="mt-3 font-display text-2xl font-black text-ice">{problem}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-mint">See the relevant route <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>)}</div></div></section>
    <section className="border-y border-border"><div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><SectionHeading eyebrow="Available offers" title="Clear scope. Clear boundaries. No inflated promise." description="Every offer states requirements, exclusions, timing and commercial status. A larger engagement is justified only when the evidence supports it." /><div className="mt-10 grid gap-6 lg:grid-cols-2">{publicOffers.map((offer) => <a key={offer.slug} href={`/offers/${offer.slug}`} className="group flex h-full flex-col rounded-3xl border border-border bg-ink p-7 transition hover:border-mint"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-mint">{offer.eyebrow}</p><h2 className="mt-3 font-display text-2xl font-black text-ice">{offer.name}</h2></div><span className="shrink-0 rounded-full border border-mint/30 bg-mint/10 px-3 py-2 text-xs font-bold text-mint">{offer.price}</span></div><p className="mt-5 flex-1 leading-relaxed text-muted-foreground">{offer.summary}</p><div className="mt-6 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2">{offer.deliverables.slice(0, 4).map((item) => <span key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-mint" />{item}</span>)}</div><span className="mt-7 inline-flex items-center gap-2 font-bold text-mint">Review scope <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>)}</div></div></section>
    <section className="bg-ink"><div className="mx-auto max-w-5xl px-6 py-20 text-center md:py-28"><p className="text-xs font-bold uppercase tracking-[.16em] text-mint">The routing rule</p><h2 className="mt-4 font-display text-4xl font-black text-ice md:text-5xl">The correct recommendation can be: do nothing yet.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-muted-foreground">If the studio has no clear constraint, no reliable baseline or no capacity to implement the change, the right next step is measurement or a simple action plan — not a larger sale.</p></div></section>
    <CtaSection />
  </PublicShell>;
}
