import { createFileRoute, Link } from "@tanstack/react-router";
import { JsonLd, PrimaryButton, PublicShell, SecondaryButton } from "@/components/public-site";

const url = "https://getinksights.co.uk/tattoo-studio-marketing";
export const Route = createFileRoute("/tattoo-studio-marketing")({
  component: Page,
  head: () => ({ meta: [
    { title: "Tattoo Studio Marketing & Growth | INKSIGHTS" },
    { name: "description", content: "Tattoo studio marketing focused on more qualified enquiries, bookings, utilisation and revenue. Built for established UK tattoo studio owners." },
  ], links: [{ rel: "canonical", href: url }] }),
});
function Page() { return <PublicShell><JsonLd data={{ "@context":"https://schema.org", "@type":"Service", name:"Tattoo Studio Marketing & Growth Intelligence", provider:{"@type":"Organization",name:"INKSIGHTS",url:"https://getinksights.co.uk"}, url }} /><main className="mx-auto max-w-7xl px-6 py-20 md:py-28"><p className="text-xs font-bold uppercase tracking-[.18em] text-mint">For UK tattoo studio owners</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-black leading-tight text-ice md:text-7xl">Tattoo studio marketing built around <span className="text-mint">commercial outcomes.</span></h1><p className="mt-7 max-w-3xl text-xl leading-relaxed text-muted-foreground">More traffic is not the objective. INKSIGHTS identifies where your studio is losing visibility, enquiries, bookings, capacity or revenue, then prioritises what is worth fixing.</p><div className="mt-9 flex flex-wrap gap-3"><PrimaryButton href="/studio-growth-check">Run the free Revenue Audit</PrimaryButton><SecondaryButton href="/tattoo-studio-visibility-scorecard">Check your visibility</SecondaryButton></div><section className="mt-20 grid gap-5 md:grid-cols-3"><Card title="Get found" text="Identify valuable local and service searches your studio should be visible for."/><Card title="Convert demand" text="Find friction between enquiries, consultations, deposits and confirmed bookings."/><Card title="Improve output" text="Connect demand, diary capacity, cancellations, retention and average booking value."/></section><section className="mt-20 max-w-4xl"><h2 className="font-display text-3xl font-black text-ice md:text-5xl">Marketing should answer a business question.</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">Which constraint is limiting the next unit of profitable growth? INKSIGHTS combines search intelligence, studio evidence and commercial diagnostics so owners can make that decision with evidence rather than another generic marketing checklist.</p><div className="mt-8 flex flex-wrap gap-5 text-sm font-bold"><Link className="text-mint hover:underline" to="/tattoo-studio-seo">Tattoo studio SEO →</Link><Link className="text-mint hover:underline" to="/tattoo-studio-revenue">Tattoo studio revenue →</Link><Link className="text-mint hover:underline" to="/tattoo-studio-booking">Tattoo studio bookings →</Link></div></section></main></PublicShell> }
function Card({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-border bg-ink-deep p-7"><h2 className="font-display text-xl font-black text-ice">{title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></div>}
