import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS = { "Access-Control-Allow-Origin": "https://getinksights.co.uk", "Access-Control-Allow-Headers": "content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Content-Type": "application/json" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: CORS });
const clean = (value: unknown, max = 300) => String(value ?? "").trim().replace(/\s+/g, " ").slice(0, max);
const list = (value: unknown) => Array.isArray(value) ? [...new Set(value.map(v => clean(v, 80)).filter(Boolean))].slice(0, 12) : [];
function publicUrl(value: unknown) { const raw = clean(value, 500); const u = new URL(/^https?:\/\//i.test(raw) ? raw : `https://${raw}`); const h = u.hostname.toLowerCase(); if (!["http:", "https:"].includes(u.protocol) || h === "localhost" || h.endsWith(".local") || h === "169.254.169.254" || h === "metadata.google.internal" || /^127\./.test(h) || /^10\./.test(h) || /^192\.168\./.test(h) || /^172\.(1[6-9]|2\d|3[0-1])\./.test(h)) throw new Error("Please enter a public website URL."); return u.toString().replace(/\/$/, ""); }
async function snapshot(site: string) { const observedAt = new Date().toISOString(); const response = await fetch(site, { redirect: "follow", headers: { "user-agent": "INKSIGHT-Visibility-Check/1.2" }, signal: AbortSignal.timeout(10000) }); const html = (await response.text()).slice(0, 2_000_000); const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim() || null; const description = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i)?.[1]?.trim() || null; const h1s = [...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map(m => m[1].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim()).filter(Boolean).slice(0, 10); const canonical = html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)?.[1] || null; const [robots, sitemap] = await Promise.allSettled([fetch(new URL("/robots.txt", response.url), { signal: AbortSignal.timeout(5000) }), fetch(new URL("/sitemap.xml", response.url), { signal: AbortSignal.timeout(5000) })]); return { http_status: response.status, final_url: response.url, title, meta_description: description, h1s, canonical, robots_available: robots.status === "fulfilled" && robots.value.ok, sitemap_available: sitemap.status === "fulfilled" && sitemap.value.ok, observed_at: observedAt }; }
function normalise(value: string) { return value.toLowerCase().replace(/[^a-z0-9\s-]/g, " ").replace(/\s+/g, " ").trim(); }
Deno.serve(async req => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ ok: false, error: "Method not allowed" }, 405);
  let studioId: string | null = null;
  try {
    const body = await req.json(); if (clean(body.website_honeypot)) return json({ ok: false, error: "Invalid submission." }, 400);
    const studioName = clean(body.studio_name,160), contactName = clean(body.contact_name,120), email = clean(body.email,254).toLowerCase(), area = clean(body.area,120), website = publicUrl(body.website), artists = Number(body.artist_count);
    const services = list(body.services), styles = list(body.styles), subjects = list(body.subjects), bodyAreas = list(body.body_areas), problemNeeds = list(body.problem_needs), customerTypes = list(body.customer_types);
    if (!studioName || !contactName || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) || !area || !Number.isInteger(artists) || artists < 3) return json({ ok: false, error: "Please provide a valid studio name, name, email, area and an artist count of 3 or more." }, 400);
    const sb = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!); const token = crypto.randomUUID().replaceAll("-", "") + crypto.randomUUID().replaceAll("-", "");
    const studioInsert = await sb.from("visibility_studios").insert({ studio_name: studioName, website_url: website, town: area, artist_count: artists, location_count: 1, average_booking_value_pence: null, monthly_search_to_booking_rate: null, status: "collecting" }).select("id").single(); if (studioInsert.error) throw new Error(`studio_insert: ${studioInsert.error.message}`); studioId = studioInsert.data.id;
    const inputSummary = { area, artist_count: artists, services, styles, subjects, body_areas: bodyAreas, problem_needs: problemNeeds, customer_types: customerTypes };
    const runInsert = await sb.from("visibility_report_runs").insert({ studio_id: studioId, report_version: "v2", status: "analysing", score_components: {}, search_demand: {}, current_visibility: {}, competitor_intelligence: {}, opportunity_summary: {}, commercial_opportunity: { status: "not_calculated" }, action_plan: {}, methodology: { provider: "website_plus_provider_pipeline", search_data: "pending" }, qa_checks: {}, data_classification: "verified_website_plus_studio_submitted", approval_required: true, public_token: token, contact_name: contactName, contact_email: email, input_summary: inputSummary }).select("id").single(); if (runInsert.error) throw new Error(`report_insert: ${runInsert.error.message}`); const runId = runInsert.data.id;
    for (const [dimension, values] of [["style", styles], ["subject", subjects], ["body_area", bodyAreas], ["problem_need", problemNeeds], ["customer_type", customerTypes]] as [string, string[]][]) { if (!values.length) continue; const capInsert = await sb.from("visibility_studio_capabilities").upsert(values.map(value => ({ studio_id: studioId, dimension, value, normalized_value: normalise(value), source_type: "studio_submitted", evidence: { report_run_id: runId } })), { onConflict: "studio_id,dimension,normalized_value" }); if (capInsert.error) throw new Error(`capability_${dimension}: ${capInsert.error.message}`); }
    const websiteData = await snapshot(website); const observationInsert = await sb.from("visibility_observations").insert({ studio_id: studioId, observation_type: "website", entity_name: website, source_provider: "studio_website", source_reference: websiteData.final_url, observed_at: websiteData.observed_at, raw_data: { ...websiteData, kind: "homepage_snapshot" } }); if (observationInsert.error) throw new Error(`website_observation: ${observationInsert.error.message}`);
    const ssuCount = await sb.from("visibility_search_universe").select("id", { count: "exact", head: true }).eq("studio_id", studioId); if (ssuCount.error) throw new Error(`ssu_count: ${ssuCount.error.message}`);
    const update = await sb.from("visibility_report_runs").update({ status: "analysing", executive_summary: "This report contains a studio-specific search universe and a source-measured website snapshot. Search demand, rankings and revenue are measured only when a configured provider and first-party attribution source are available.", search_demand: { provider: "pending", generated_searches: ssuCount.count ?? 0 }, current_visibility: { provider: "pending", rankings_measured: 0 }, opportunity_summary: { status: "candidate_unverified", search_universe_count: ssuCount.count ?? 0 }, commercial_opportunity: { status: "not_calculated", reason: "First-party attribution and conversion data are not connected." }, action_plan: { actions: [] }, methodology: { provider: "website_plus_provider_pipeline", search_universe: "studio-specific generated candidates", revenue: "not calculated" }, qa_checks: { website_http_status: websiteData.http_status, website_title_present: Boolean(websiteData.title), ssu_count: ssuCount.count ?? 0, financial_assumptions_used: false }, data_classification: "verified_website_plus_studio_submitted", approval_required: true }).eq("id", runId); if (update.error) throw new Error(`report_update: ${update.error.message}`);
    const functionUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/search-intelligence-v1`;
    EdgeRuntime.waitUntil(fetch(functionUrl, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}` }, body: JSON.stringify({ report_run_id: runId }) }).catch(error => console.error("search-intelligence-trigger", error)));
    return json({ ok: true, reportId: runId, publicToken: token, status: "analysing", provider: "website_plus_provider_pipeline", searchUniverseCount: ssuCount.count ?? 0, searchPipeline: "started", reportUrl: `https://getinksights.co.uk/studio-visibility-report?reportId=${runId}&token=${token}` });
  } catch (error) { console.error(error); return json({ ok: false, error: error instanceof Error ? error.message : "Unable to generate the report.", studioId }, 500); }
});
