import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS = { "Access-Control-Allow-Origin": "https://getinksights.co.uk", "Access-Control-Allow-Headers": "content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Content-Type": "application/json" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: CORS });
const clean = (value: unknown, max = 500) => String(value ?? "").trim().replace(/\s+/g, " ").slice(0, max);
const list = (value: unknown) => Array.isArray(value) ? [...new Set(value.map(v => clean(v, 120)).filter(Boolean))].slice(0, 12) : [];
function publicUrl(value: unknown) { const raw = clean(value, 1000); if (!raw) throw new Error("A public website URL is required."); const u = new URL(/^https?:\/\//i.test(raw) ? raw : `https://${raw}`); const h = u.hostname.toLowerCase(); if (!["http:", "https:"].includes(u.protocol) || h === "localhost" || h.endsWith(".local") || h === "169.254.169.254" || h === "metadata.google.internal" || /^127\./.test(h) || /^10\./.test(h) || /^192\.168\./.test(h) || /^172\.(1[6-9]|2\d|3[0-1])\./.test(h)) throw new Error("Please enter a public website URL."); return u.toString().replace(/\/$/, ""); }
function optionalUrl(value: unknown) { try { return value ? publicUrl(value) : null; } catch { return null; } }
async function snapshot(site: string) { const observedAt = new Date().toISOString(); const response = await fetch(site, { redirect: "follow", headers: { "user-agent": "INKSIGHT-Studio-Intelligence/1.0" }, signal: AbortSignal.timeout(10000) }); const html = (await response.text()).slice(0, 2_000_000); const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim() || null; const description = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i)?.[1]?.trim() || null; const h1s = [...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map(m => m[1].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim()).filter(Boolean).slice(0, 10); const canonical = html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)?.[1] || null; const text = html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 20000); const [robots, sitemap] = await Promise.allSettled([fetch(new URL("/robots.txt", response.url), { signal: AbortSignal.timeout(5000) }), fetch(new URL("/sitemap.xml", response.url), { signal: AbortSignal.timeout(5000) })]); return { http_status: response.status, final_url: response.url, title, meta_description: description, h1s, canonical, robots_available: robots.status === "fulfilled" && robots.value.ok, sitemap_available: sitemap.status === "fulfilled" && sitemap.value.ok, text_sample: text, observed_at: observedAt }; }
function normalise(value: string) { return value.toLowerCase().replace(/[^a-z0-9\s-]/g, " ").replace(/\s+/g, " ").trim(); }
const infer = (text: string, dictionary: string[]) => { const haystack = text.toLowerCase(); return dictionary.filter(term => haystack.includes(term.toLowerCase())).slice(0, 12); };
const styleDictionary = ["black and grey","blackwork","fine line","realism","micro realism","colour","traditional","neo traditional","ornamental","geometric","watercolour","chicano","japanese","dotwork","minimalist"];
const serviceDictionary = ["tattoo","tattooing","piercing","tattoo removal","cover up","cover-up","consultation","aftercare"];
const bodyDictionary = ["sleeve","back","chest","leg","arm","forearm","thigh","calf","hand","neck","ribs","ankle"];
Deno.serve(async req => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ ok: false, error: "Method not allowed" }, 405);
  let studioId: string | null = null;
  try {
    const body = await req.json(); if (clean(body.website_honeypot)) return json({ ok: false, error: "Invalid submission." }, 400);
    const studioName = clean(body.studio_name,160), contactName = clean(body.contact_name,120), email = clean(body.email,254).toLowerCase(), area = clean(body.area,120), website = publicUrl(body.website);
    const googleUrl = optionalUrl(body.google_url); const socialUrls = list(body.social_urls).map(optionalUrl).filter(Boolean) as string[]; const artistCount = Number(body.artist_count);
    if (!studioName || !contactName || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) || !area || !Number.isInteger(artistCount) || artistCount < 1) return json({ ok:false, error:"Please provide a valid studio name, name, email, area and artist count." },400);
    const sb = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!); const token = crypto.randomUUID().replaceAll("-", "") + crypto.randomUUID().replaceAll("-", "");
    const studioInsert = await sb.from("visibility_studios").insert({ studio_name: studioName, website_url: website, town: area, artist_count: artistCount, location_count: 1, average_booking_value_pence: null, monthly_search_to_booking_rate: null, status: "collecting" }).select("id").single(); if (studioInsert.error) throw new Error(`studio_insert: ${studioInsert.error.message}`); studioId = studioInsert.data.id;
    const websiteData = await snapshot(website); const submittedServices = list(body.services), submittedStyles = list(body.styles), submittedBodies = list(body.body_areas); const sourceText = `${websiteData.title || ""} ${websiteData.meta_description || ""} ${websiteData.text_sample || ""}`; const inferredServices = infer(sourceText, serviceDictionary), inferredStyles = infer(sourceText, styleDictionary), inferredBodies = infer(sourceText, bodyDictionary); const finalServices = submittedServices.length ? submittedServices : inferredServices, finalStyles = submittedStyles.length ? submittedStyles : inferredStyles, finalBodies = submittedBodies.length ? submittedBodies : inferredBodies;
    const inputSummary = { area, artist_count: artistCount, website, google_url: googleUrl, social_urls: socialUrls, submitted: { services: submittedServices, styles: submittedStyles, body_areas: submittedBodies }, inferred_from_website: { services: inferredServices, styles: inferredStyles, body_areas: inferredBodies } };
    const runInsert = await sb.from("visibility_report_runs").insert({ studio_id: studioId, report_version:"v2", status:"collecting", score_components:{}, search_demand:{}, current_visibility:{}, competitor_intelligence:{}, opportunity_summary:{}, commercial_opportunity:{status:"not_calculated"}, action_plan:{}, methodology:{provider:"website_plus_search_provider",search_data:"pending"}, qa_checks:{}, data_classification:"external_unverified", approval_required:true, public_token:token, contact_name:contactName, contact_email:email, input_summary:inputSummary }).select("id").single(); if (runInsert.error) throw new Error(`report_insert: ${runInsert.error.message}`); const runId = runInsert.data.id;
    for (const [dimension, values, source] of [["service", finalServices, submittedServices.length ? "studio_submitted" : "website_verified"],["style", finalStyles, submittedStyles.length ? "studio_submitted" : "website_verified"],["body_area", finalBodies, submittedBodies.length ? "studio_submitted" : "website_verified"]] as [string,string[],string][]) { if (!values.length) continue; const capInsert = await sb.from("visibility_studio_capabilities").upsert(values.map(value => ({ studio_id:studioId, dimension, value, normalized_value:normalise(value), source_type:source, evidence:{ report_run_id:runId }, confidence: source === "studio_submitted" ? 1 : 0.65 })), { onConflict:"studio_id,dimension,normalized_value" }); if (capInsert.error) throw new Error(`capability_${dimension}: ${capInsert.error.message}`); }
    const observationInsert = await sb.from("visibility_observations").insert({ studio_id:studioId, observation_type:"website", entity_name:website, source_provider:"studio_website", source_reference:websiteData.final_url, observed_at:websiteData.observed_at, raw_data:{...websiteData,kind:"homepage_snapshot"} }); if (observationInsert.error) throw new Error(`website_observation: ${observationInsert.error.message}`);
    for (const [type,url] of [["google_profile",googleUrl],["social_profile",socialUrls[0] || null]] as [string,string|null][]) if (url) await sb.from("visibility_observations").insert({ studio_id:studioId, observation_type:"manual", entity_name:url, source_provider:"submitted_public_source", source_reference:url, raw_data:{kind:type,status:"submitted_not_verified"} });
    const rpc = await sb.rpc("generate_studio_search_universe", { p_studio_id: studioId, p_report_run_id: runId }); if (rpc.error) throw new Error(`search_universe_generation: ${rpc.error.message}`); const ssuCount = Number(rpc.data || 0);
    await sb.from("visibility_report_runs").update({ executive_summary:`Initial public-footprint snapshot created for ${studioName}. Website evidence has been captured and a studio-specific search universe has been generated. Search demand, rankings and commercial opportunity are only presented as measured when an external search provider returns source data.`, search_demand:{provider:"pending",generated_searches:ssuCount}, current_visibility:{provider:"pending",rankings_measured:0}, opportunity_summary:{status:"awaiting_search_measurement",search_universe_count:ssuCount}, commercial_opportunity:{status:"not_calculated",reason:"No first-party booking/conversion attribution is connected at acquisition stage."}, action_plan:{actions:[]}, methodology:{provider:"website_plus_search_provider",search_universe:"studio capabilities + local area",revenue:"not calculated"}, qa_checks:{website_http_status:websiteData.http_status,website_title_present:Boolean(websiteData.title),ssu_count:ssuCount,financial_assumptions_used:false}, data_classification:"external_unverified", approval_required:true }).eq("id",runId);
    const functionUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/search-intelligence-v1`; EdgeRuntime.waitUntil(fetch(functionUrl,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`},body:JSON.stringify({report_run_id:runId})}).catch(error=>console.error("search-intelligence-trigger",error)));
    return json({ok:true,reportId:runId,publicToken:token,status:"collecting",searchUniverseCount:ssuCount,searchPipeline:"started",reportUrl:`https://getinksights.co.uk/studio-visibility-report?reportId=${runId}&token=${token}`});
  } catch(error) { console.error(error); return json({ok:false,error:error instanceof Error?error.message:"Unable to generate the report.",studioId},500); }
});
