import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type Json = Record<string, unknown>;
type SearchRow = { id:string; query:string; canonical_query:string; demand:number; commercial_intent:number; local_relevance:number; conversion_potential:number; studio_relevance:number; capability:number };
const CORS={"Access-Control-Allow-Origin":"https://getinksights.co.uk","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
const clean=(v:unknown,max=500)=>String(v??"").trim().replace(/\s+/g," ").slice(0,max);
const domainOf=(url:string|null)=>{try{return new URL(url??"").hostname.replace(/^www\./,"").toLowerCase()}catch{return ""}};
const demandScore=(volume:number)=>Math.round(Math.max(0,Math.min(100,20+Math.log(Math.max(volume,0)+1)*12))*100)/100;
const rankOpportunity=(rank:number|null)=>rank===null?100:rank<=3?15:rank<=10?55:rank<=20?80:100;
const lso=(d:number,i:number,l:number,p:number,c:number,r:number,cap:number)=>Math.round(Math.max(0,Math.min(100,(d*i*l*p*c*r*cap)/1e12))*100)/100;
async function dfs(path:string,body:unknown,login:string,password:string){const auth=btoa(`${login}:${password}`);const response=await fetch(`https://api.dataforseo.com/v3/${path}`,{method:"POST",headers:{Authorization:`Basic ${auth}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const text=await response.text();let data:Json;try{data=JSON.parse(text)}catch{throw new Error(`dataforseo_invalid_response:${response.status}`)}if(!response.ok||data.status_code!==20000)throw new Error(`dataforseo_error:${response.status}:${clean(data.status_message,240)}`);return data}
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS}); if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);
 let pipelineId:string|null=null;
 try{
  const body=await req.json();const reportRunId=clean(body.report_run_id,80);if(!reportRunId)return json({ok:false,error:"report_run_id is required"},400);
  const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const run=await sb.from("visibility_report_runs").select("id,studio_id,status").eq("id",reportRunId).single();if(run.error)throw new Error(`report_lookup:${run.error.message}`);
  const studio=await sb.from("visibility_studios").select("id,studio_name,website_url,town").eq("id",run.data.studio_id).single();if(studio.error)throw new Error(`studio_lookup:${studio.error.message}`);
  const provider=(Deno.env.get("SEARCH_DATA_PROVIDER")??"dataforseo").toLowerCase();const login=Deno.env.get("DATAFORSEO_LOGIN")??"";const password=Deno.env.get("DATAFORSEO_PASSWORD")??"";
  const pipe=await sb.from("visibility_pipeline_runs").insert({studio_id:studio.data.id,report_run_id:reportRunId,provider,stage:"search_intelligence",status:"started",input_payload:{provider}}).select("id").single();if(pipe.error)throw new Error(`pipeline_insert:${pipe.error.message}`);pipelineId=pipe.data.id;
  if(provider!=="dataforseo"||!login||!password){await sb.from("visibility_pipeline_runs").update({status:"blocked",error_message:provider!=="dataforseo"?`Provider ${provider} is not implemented`:"DATAFORSEO_LOGIN/DATAFORSEO_PASSWORD not configured",completed_at:new Date().toISOString()}).eq("id",pipelineId);return json({ok:false,status:"blocked",provider,pipelineRunId:pipelineId},503)}
  const rows=await sb.from("visibility_search_universe").select("id,query,canonical_query,demand,commercial_intent,local_relevance,conversion_potential,studio_relevance,capability").eq("report_run_id",reportRunId).eq("semantic_valid",true).limit(1000);if(rows.error)throw new Error(`search_universe_lookup:${rows.error.message}`);const searches=(rows.data??[]) as SearchRow[];if(!searches.length)throw new Error("search_universe_empty");
  const now=new Date().toISOString();let volumeWritten=0;const location=`${studio.data.town}, United Kingdom`;
  const api=await dfs("keywords_data/google_ads/search_volume/live",[{keywords:searches.map(x=>x.query),language_code:"en",location_name:location,include_serp_info:false}],login,password);const task=(api.tasks as Json[]|undefined)?.[0];const result=(task?.result as Json[]|undefined)?.[0];const items=(result?.items as Json[]|undefined)??[];
  await sb.from("visibility_provider_observations").insert({pipeline_run_id:pipelineId,report_run_id:reportRunId,studio_id:studio.data.id,provider:"dataforseo",endpoint:"keywords_data/google_ads/search_volume/live",request_payload:{keyword_count:searches.length,location_name:location,language_code:"en"},response_payload:{status_code:api.status_code,task_status_code:task?.status_code,cost:task?.cost,result_count:items.length},response_status:200,units_consumed:Number(task?.cost??api.cost??0),observed_at:now});
  for(const item of items){const keyword=clean(item.keyword,500).toLowerCase();const match=searches.find(x=>x.query.toLowerCase()===keyword||x.canonical_query.toLowerCase()===keyword);if(!match)continue;const volume=Number(item.search_volume??0);const d=demandScore(volume);const upd=await sb.from("visibility_search_universe").update({demand:d,dimension_values:{provider:"dataforseo",search_volume:volume,cpc_usd:Number(item.cpc??0),competition:Number(item.competition??0),monthly_searches:item.monthly_searches??[]},updated_at:now}).eq("id",match.id);if(upd.error)throw new Error(`volume_update:${upd.error.message}`);volumeWritten++}
  const refreshed=await sb.from("visibility_search_universe").select("id,query,canonical_query,demand,commercial_intent,local_relevance,conversion_potential,studio_relevance,capability").eq("report_run_id",reportRunId).eq("semantic_valid",true).order("demand",{ascending:false}).limit(30);if(refreshed.error)throw new Error(`search_universe_refresh:${refreshed.error.message}`);const top=(refreshed.data??[]) as SearchRow[];
  const studioDomain=domainOf(studio.data.website_url);let serpWritten=0;const competitorDomains=new Set<string>();const ranks:number[]=[];
  for(const row of top){const api2=await dfs("serp/google/organic/live/regular",[{keyword:row.query,location_name:location,language_code:"en",device:"desktop",depth:10}],login,password);const task2=(api2.tasks as Json[]|undefined)?.[0];const result2=(task2?.result as Json[]|undefined)?.[0];const serps=(result2?.items as Json[]|undefined)??[];let rank:number|null=null;const obs=serps.map(item=>{const pos=Number(item.rank_absolute??item.rank_group??0)||null;const domain=domainOf(clean(item.domain??item.url));const isStudio=Boolean(studioDomain&&domain===studioDomain);if(isStudio&&rank===null)rank=pos;if(domain&&!isStudio&&pos&&pos<=10)competitorDomains.add(domain);return{studio_id:studio.data.id,report_run_id:reportRunId,search_universe_id:row.id,query:row.query,database:"google.co.uk",result_position:pos,result_type:clean(item.type,80),domain:clean(item.domain,500)||null,url:clean(item.url,1000)||null,title:clean(item.title,500)||null,is_studio:isStudio,is_competitor:!isStudio&&Boolean(domain),source_provider:"dataforseo",observed_at:now,raw_data:item}});if(obs.length){const ins=await sb.from("visibility_serp_observations").insert(obs);if(ins.error)throw new Error(`serp_insert:${ins.error.message}`);serpWritten+=obs.length}const score=lso(Number(row.demand),Number(row.commercial_intent),Number(row.local_relevance),rankOpportunity(rank),Number(row.conversion_potential),Number(row.studio_relevance),Number(row.capability));const upd=await sb.from("visibility_search_universe").update({current_position:rank,serp_features:{top10_results:serps.slice(0,10).map(x=>({rank:x.rank_absolute,domain:x.domain,type:x.type}))},lsos:score,status:rank!==null&&rank<=10?"defend":"opportunity",updated_at:now}).eq("id",row.id);if(upd.error)throw new Error(`serp_update:${upd.error.message}`);if(rank!==null)ranks.push(rank)}
  for(const domain of [...competitorDomains].slice(0,25)){const ins=await sb.from("visibility_competitor_observations").insert({studio_id:studio.data.id,report_run_id:reportRunId,competitor_name:domain,domain,query:"SERP-derived competitor",rank:null,visibility_share:null,keyword_overlap:0,source_provider:"dataforseo",observed_at:now,raw_data:{derived_from:"top_demand_serps"}});if(ins.error)throw new Error(`competitor_insert:${ins.error.message}`)}
  const avg=ranks.length?Math.round(ranks.reduce((a,b)=>a+b,0)/ranks.length*10)/10:null;const done=await sb.from("visibility_pipeline_runs").update({status:"success",records_read:searches.length,records_written:volumeWritten+serpWritten,output_payload:{volume_keywords:volumeWritten,serp_queries:top.length,serp_observations:serpWritten,competitor_domains:competitorDomains.size,observed_studio_ranks:ranks.length,average_observed_rank:avg},completed_at:new Date().toISOString()}).eq("id",pipelineId);if(done.error)throw new Error(`pipeline_update:${done.error.message}`);
  const report=await sb.from("visibility_report_runs").update({status:"qa",search_demand:{provider:"dataforseo",keywords_measured:volumeWritten,generated_candidates:searches.length},current_visibility:{provider:"dataforseo",serp_queries:top.length,observed_ranks:ranks.length,average_rank:avg},competitor_intelligence:{provider:"dataforseo",competitor_domains:[...competitorDomains].slice(0,25)},commercial_opportunity:{status:"not_calculated",reason:"First-party conversion/booking attribution is not connected."},methodology:{provider:"dataforseo",demand:"Google Ads-derived search volume",serp:"Google organic SERP observations",ranking_selection:"top 30 after observed demand refresh",revenue:"not calculated until first-party attribution is connected"},qa_checks:{provider_run_completed:true,keywords_measured:volumeWritten,serp_queries:top.length,observed_ranks:ranks.length}}).eq("id",reportRunId);if(report.error)throw new Error(`report_update:${report.error.message}`);
  return json({ok:true,status:"success",provider:"dataforseo",reportRunId,pipelineRunId:pipelineId,keywordsMeasured:volumeWritten,serpQueries:top.length,serpObservations:serpWritten,competitorDomains:[...competitorDomains].slice(0,25)});
 }catch(error){if(pipelineId){try{const sb=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);await sb.from("visibility_pipeline_runs").update({status:"failed",error_message:error instanceof Error?error.message:"unknown_error",completed_at:new Date().toISOString()}).eq("id",pipelineId)}catch{}}console.error(error);return json({ok:false,status:"failed",error:error instanceof Error?error.message:"Unable to run search intelligence.",pipelineRunId:pipelineId},500)}});
