'use client';
import {useState,type ReactNode} from 'react';
import {format,factor,type Manifest} from '@/lib/contract';
export const sections=[['executive','Executive Intelligence'],['score','Studio Intelligence Score'],['commercial','Commercial Performance'],['demand','Demand / Visibility'],['funnel','Enquiry & Booking Funnel'],['capacity','Capacity / Utilisation'],['retention','Retention / Rebooking'],['pricing','Pricing / Revenue'],['competition','Competitive Position'],['findings','Findings'],['opportunities','Opportunities'],['recommendations','Recommendations'],['plan','90-Day Plan'],['evidence','Evidence'],['methodology','Methodology']];
export type Progress={recommendation_id:string;status:string;intervention:string;outcome:string;attribution:string;learning:string;updated_at:string};
export function Report({report,version=1,status='Reference',pdfHref='/golden/pdf',progress=[]}:{report:Manifest;version?:number;status?:string;pdfHref?:string;progress?:Progress[]}){
const {input,metrics}=report;const [series,setSeries]=useState<'revenue'|'completed'>('revenue');const [search,setSearch]=useState('');
const get=(k:string)=>metrics.find(m=>m.key===k)!;const sum=(k:keyof typeof input.months[number])=>input.months.some(m=>m[k]===null)?null:input.months.reduce((n,m)=>n+Number(m[k]),0);
const max=Math.max(1,...input.months.map(m=>m[series]??0));
return <div className="report-shell"><aside className="rail no-print"><a href="/" aria-label="INKSIGHTS reports"><img className="logo" src="/brand/logo-v3/primary-dark.svg" alt="INKSIGHTS"/></a><div className="rail-label">STUDIO INTELLIGENCE</div><p className="rail-studio">{input.studio.name}</p><nav aria-label="Report sections">{sections.map(([id,label],i)=><a key={id} href={`#${id}`}><span>{String(i+1).padStart(2,'0')}</span>{label}</a>)}</nav><div className="rail-foot"><span className="dot"/> {status} · v{version}<br/><small>Intelligence into action.</small></div></aside>
<div className="report-body"><header className="topbar no-print"><a href="/">← Reports</a><span>{input.studio.location}</span><a className="button" href={pdfHref}>↓ Download PDF</a></header><nav className="mobile-nav no-print" aria-label="Mobile report sections">{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
<main id="main"><section id="executive" className="hero report-section"><div className="eyebrow"><span className="dot"/> STUDIO INTELLIGENCE REPORT <span className="badge">{input.representative?'FICTIONAL REFERENCE':status.toUpperCase()}</span></div><div className="hero-heading"><div><p className="period">{input.period.start} — {input.period.end} · Version {version}</p><h1>{input.studio.name}<span>See what matters.<br/>Know what to do next.</span></h1></div><img className="signature" src="/brand/logo-v3/icon-flat.svg" alt="Official INKSIGHTS three-bar mark"/></div>
<div className="answer"><span className="eyebrow">THE PRINCIPAL FINDING</span><h2>{input.findings[0].title}</h2><p>{input.findings[0].answer}</p><a href="#findings">Explore the evidence <span aria-hidden>↗</span></a></div><div className="metrics-grid">{['revenue','conversion','utilisation','rebooking'].map(k=><MetricCard key={k} metric={get(k)}/>)}</div><p className="disclaimer">{input.representative?'Representative data only. No real studio, client result or case study is implied.':input.limitations[0]}</p></section>
<Section id="score" index="02" title="Studio Intelligence Score" subtitle="A planning index. Every target is visible."><div className="score-layout"><div className="score-orbit" style={{'--score':`${(report.score??0)*3.6}deg`} as React.CSSProperties}><div><strong>{report.score??'—'}</strong><span>{report.score===null?'Insufficient evidence':'/ 100 · diagnostic index'}</span></div></div><div><div className="dimension-list">{(['conversion','utilisation','rebooking'] as const).map(k=><div key={k}><div className="spread"><strong>{get(k).label}</strong><span>{format(get(k).value,'%')} <small>/ {input.targets[k]}% target</small></span></div><div className="track"><div style={{width:`${Math.min(100,(get(k).value??0)/input.targets[k]*100)}%`}}/></div></div>)}</div><p>{input.targets.rationale}</p><p className="meta">{report.scoreCoverage}/3 dimensions measured · Equal weights · {get('conversion').confidence.toLowerCase()} evidence confidence</p><a href="#methodology">How this score is calculated →</a></div></div></Section>
<Section id="commercial" index="03" title="Commercial Performance" subtitle="The monthly picture, without hiding the underlying numbers."><div className="spread"><p>Revenue is after refunds, before operating costs.</p><div className="segmented no-print" aria-label="Chart measure">{(['revenue','completed'] as const).map(s=><button key={s} aria-pressed={series===s} onClick={()=>setSeries(s)}>{s==='revenue'?'Revenue':'Appointments'}</button>)}</div></div><div className="bar-chart" role="img" aria-label={`Monthly ${series}; exact values in the table below.`}>{input.months.map(m=><div className="bar-column" key={m.month}><strong>{format(m[series],series==='revenue'?'GBP':'count')}</strong><div className="bar-well"><div className="bar" style={{height:`${m[series]===null?0:Math.max(1,m[series]/max*100)}%`}}/></div><span>{new Date(`${m.month}-01T12:00:00Z`).toLocaleDateString('en-GB',{month:'short',year:'2-digit'})}</span></div>)}</div><div className="table-wrap"><table><caption>Monthly commercial data</caption><thead><tr><th>Month</th><th>Net revenue</th><th>Appointments</th><th>Enquiries</th><th>Bookings</th></tr></thead><tbody>{input.months.map(m=><tr key={m.month}><th>{m.month}</th><td>{format(m.revenue,'GBP')}</td><td>{format(m.completed)}</td><td>{format(m.enquiries)}</td><td>{format(m.bookings)}</td></tr>)}</tbody></table></div></Section>
<div className="section-pair"><Section id="demand" index="04" title="Demand / Visibility" subtitle="Attention is the start of a journey, not a booking."><div className="mini-grid"><Stat label="Search views" value={format(sum('searchViews'))}/><Stat label="Tracked actions" value={format(sum('searchActions'))}/></div><MetricCard metric={get('searchActionRate')}/><p>Search actions may repeat. They are not unique leads or proven revenue attribution.</p></Section><Section id="funnel" index="05" title="Enquiry & Booking Funnel" subtitle="Measure the handover from interest to a confirmed booking."><div className="funnel"><div><span>Recorded enquiries</span><strong>{format(sum('enquiries'))}</strong></div><span className="funnel-arrow">↓</span><div><span>Confirmed cohort bookings</span><strong>{format(sum('bookings'))}</strong></div></div><MetricCard metric={get('conversion')}/></Section></div>
<div className="section-pair"><Section id="capacity" index="06" title="Capacity / Utilisation" subtitle="Turn genuinely available artist time into appropriate bookings."><div className="mini-grid"><Stat label="Booked hours" value={format(sum('bookedHours'))}/><Stat label="Available hours" value={format(sum('availableHours'))}/></div><MetricCard metric={get('utilisation')}/><p>Availability excludes planned time off. Aggregate figures can hide artist and day-of-week differences.</p></Section><Section id="retention" index="07" title="Retention / Rebooking" subtitle="A useful next session, offered at the right moment."><div className="mini-grid"><Stat label="Eligible clients" value={format(sum('eligibleClients'))}/><Stat label="With next booking" value={format(sum('rebookedClients'))}/></div><MetricCard metric={get('rebooking')}/><p>This measures next bookings among eligible clients. It does not measure lifetime retention or client value.</p></Section></div>
<Section id="pricing" index="08" title="Pricing / Revenue" subtitle="Understand the value of completed work and available time."><div className="mini-grid"><MetricCard metric={get('averageValue')}/><MetricCard metric={get('revenuePerHour')}/></div><p>Appointment mix, duration and artist specialism affect these measures. An average alone is not evidence that prices should increase.</p></Section>
<Section id="competition" index="09" title="Competitive Position" subtitle="Specific observations, with dated evidence.">{input.competitors.length?input.competitors.map(c=><div className="observation" key={c.name}><h3>{c.name}</h3><p>{c.observation}</p><a href={`#evidence-${c.evidenceId}`}>Source: {c.evidenceId} →</a></div>):<p className="empty">Not assessed. Add dated, comparable competitor evidence before drawing a market-position conclusion.</p>}</Section>
<Section id="findings" index="10" title="Findings" subtitle="An answer you can trace back to its evidence.">{input.findings.map((f,i)=><article className="finding" key={f.id} id={`finding-${f.id}`}><div className="finding-number">{String(i+1).padStart(2,'0')}</div><div><div className="eyebrow">{f.category} <span className="badge">{f.materiality} priority</span></div><h3>{f.title}</h3><p className="lead">{f.answer}</p><div className="evidence-links">{f.evidenceIds.map(e=><a key={e} href={`#evidence-${e}`}>{e} ↗</a>)}</div><details open><summary>Explanation & alternative</summary><p>{f.diagnosis}</p><p><strong>Also consider:</strong> {f.alternative}</p></details><a href="#recommendations">See the recommended action →</a></div></article>)}</Section>
<Section id="opportunities" index="11" title="Opportunities" subtitle="Prioritise a credible test before expanding the programme.">{report.opportunities.map((r,i)=><div className="opportunity" key={r.id}><span className="rank">{i+1}</span><div><h3>{r.title}</h3><p>{r.assumptions}</p><span className="meta">Impact {r.impact} × confidence {factor[r.confidence]} × urgency {r.urgency} ÷ effort {r.effort}</span></div><div className="rank-score"><strong>{r.rank}</strong><small>priority score</small></div></div>)}</Section>
<Section id="recommendations" index="12" title="Recommendations" subtitle="Clear ownership. A concrete next step. A measure of progress.">{report.opportunities.map(r=><article className="recommendation" key={r.id}><div className="eyebrow">{r.confidence} CONFIDENCE · DAYS {r.phase}</div><h3>{r.title}</h3><p>{r.action}</p><div className="spread meta"><span>Owner: {r.owner}</span><span>Measure: {get(r.targetMetric).label}</span></div><a href={`#finding-${r.findingId}`}>Linked finding →</a></article>)}</Section>
<Section id="plan" index="13" title="Your next 90 days" subtitle="A small, measurable programme the studio can actually deliver." light><div className="plan-grid">{(['1–30','31–60','61–90'] as const).map(phase=><div className="plan-phase" key={phase}><div className="eyebrow">DAYS {phase}</div>{input.recommendations.filter(r=>r.phase===phase).map(r=>{const p=progress.find(p=>p.recommendation_id===r.id);return <div key={r.id}><h3>{r.title}</h3><p>{r.owner}</p><span className="badge">{p?.status?.replaceAll('_',' ')??'Not started'}</span>{p?.intervention&&<p><strong>Intervention:</strong> {p.intervention}</p>}{p?.outcome&&<p><strong>Outcome:</strong> {p.outcome}</p>}{p?.attribution&&<p><strong>Attribution:</strong> {p.attribution}</p>}{p?.learning&&<p><strong>Learning:</strong> {p.learning}</p>}</div>})}</div>)}</div><p className="meta">Progress is a separate dated record. The approved report remains unchanged.</p></Section>
<Section id="evidence" index="14" title="Evidence" subtitle="What we know, where it came from, and what it cannot tell us."><label className="search no-print">Find evidence<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search sources, IDs or observations…"/></label><div aria-live="polite" className="meta no-print">{input.evidence.filter(e=>JSON.stringify(e).toLowerCase().includes(search.toLowerCase())).length} sources shown</div>{input.evidence.map(e=><article id={`evidence-${e.id}`} key={e.id} className={`evidence-item ${!JSON.stringify(e).toLowerCase().includes(search.toLowerCase())?'filtered':''}`}><div className="spread"><h3>{e.title}</h3><span className="badge">{e.classification} · {e.confidence}</span></div><p>{e.summary}</p><p className="meta">{e.id} · Observed {e.observedAt}<br/>Source: {e.source}</p><p><strong>Limit:</strong> {e.limitations||'No additional limitations recorded.'}</p></article>)}</Section>
<Section id="methodology" index="15" title="Methodology" subtitle="An explicit chain from observation to learning."><div className="method-chain">{['Observation','Normalised Data','Metric','Evidence','Finding','Diagnosis','Opportunity','Recommendation','Intervention','Outcome','Attribution','Learning'].map(s=><span key={s}>{s}</span>)}</div><h3>How to read the numbers</h3><p>All figures cover {input.period.start} to {input.period.end}. Missing inputs and zero denominators remain unmeasured. Confidence is the lowest level in the supporting metric evidence, not a statistical probability.</p><div className="table-wrap"><table><caption>Calculation catalogue · version {report.calculationVersion}</caption><thead><tr><th>Metric</th><th>Formula</th></tr></thead><tbody>{metrics.map(m=><tr key={m.key}><th>{m.label}</th><td>{m.formula}</td></tr>)}</tbody></table></div><p>The score averages three equally weighted dimensions: min(100, measured rate ÷ supplied target × 100). All three must be measurable. Opportunity scores express relative priorities, not expected money. No industry comparison or causal claim is implied.</p><h3>Limitations</h3><ul>{input.limitations.map(l=><li key={l}>{l}</li>)}</ul></Section>
<footer className="report-footer"><img src="/brand/logo-v3/primary-dark.svg" alt="INKSIGHTS"/><p>Studio intelligence. Grounded in evidence.<br/><small>Version {version} · Calculation {report.calculationVersion} · {input.representative?'Fictional reference':'Confidential client report'}</small></p></footer></main></div></div>;
}
function Section({id,index,title,subtitle,children,light=false}:{id:string;index:string;title:string;subtitle:string;children:ReactNode;light?:boolean}){return <section id={id} className={`report-section panel ${light?'light':''}`}><div className="eyebrow">{index} / INTELLIGENCE</div><h2>{title}</h2><p className="section-subtitle">{subtitle}</p>{children}</section>}
function MetricCard({metric:m}:{metric:Manifest['metrics'][number]}){return <div className="metric"><span>{m.label}</span><strong>{format(m.value,m.unit)}</strong><small>{m.value===null?m.reason:`${m.confidence.toLowerCase()} confidence · ${m.formula}`}</small><div className="metric-sources">{m.evidenceIds.map(id=><a key={id} href={`#evidence-${id}`}>{id}</a>)}</div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
