/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TattooStudioVisibilityScorecardRouteImport } from './routes/tattoo-studio-visibility-scorecard'
import { Route as TattooStudioSoftwareRouteImport } from './routes/tattoo-studio-software'
import { Route as TattooStudioSeoRouteImport } from './routes/tattoo-studio-seo'
import { Route as TattooStudioRevenueRouteImport } from './routes/tattoo-studio-revenue'
import { Route as TattooStudioMarketingRouteImport } from './routes/tattoo-studio-marketing'
import { Route as TattooStudioManagementRouteImport } from './routes/tattoo-studio-management'
import { Route as TattooStudioGrowthRouteImport } from './routes/tattoo-studio-growth'
import { Route as TattooStudioClientRetentionRouteImport } from './routes/tattoo-studio-client-retention'
import { Route as TattooStudioBookingRouteImport } from './routes/tattoo-studio-booking'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudioVisibilityReportRouteImport } from './routes/studio-visibility-report'
import { Route as StudioGrowthCheckRouteImport } from './routes/studio-growth-check'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingBenchmarkRouteImport } from './routes/pricing-benchmark'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GrowthModelRouteImport } from './routes/growth-model'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ToolsTattooPainChartRealityCheckRouteImport } from './routes/tools.tattoo-pain-chart-reality-check'
import { Route as OffersSlugRouteImport } from './routes/offers._slug'
import { Route as GuidesGreyLineHealingWeekByWeekRouteImport } from './routes/guides.grey-line-healing-week-by-week'
import { Route as GuidesFullSleeveCostUkRouteImport } from './routes/guides.full-sleeve-cost-uk'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as DotLovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioVisibilityScorecardRoute =
  TattooStudioVisibilityScorecardRouteImport.update({
    id: '/tattoo-studio-visibility-scorecard',
    path: '/tattoo-studio-visibility-scorecard',
    getParentRoute: () => rootRouteImport,
  } as any)
const TattooStudioSoftwareRoute = TattooStudioSoftwareRouteImport.update({
  id: '/tattoo-studio-software',
  path: '/tattoo-studio-software',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioSeoRoute = TattooStudioSeoRouteImport.update({
  id: '/tattoo-studio-seo',
  path: '/tattoo-studio-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioRevenueRoute = TattooStudioRevenueRouteImport.update({
  id: '/tattoo-studio-revenue',
  path: '/tattoo-studio-revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioMarketingRoute = TattooStudioMarketingRouteImport.update({
  id: '/tattoo-studio-marketing',
  path: '/tattoo-studio-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioManagementRoute = TattooStudioManagementRouteImport.update({
  id: '/tattoo-studio-management',
  path: '/tattoo-studio-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioGrowthRoute = TattooStudioGrowthRouteImport.update({
  id: '/tattoo-studio-growth',
  path: '/tattoo-studio-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioClientRetentionRoute =
  TattooStudioClientRetentionRouteImport.update({
    id: '/tattoo-studio-client-retention',
    path: '/tattoo-studio-client-retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const TattooStudioBookingRoute = TattooStudioBookingRouteImport.update({
  id: '/tattoo-studio-booking',
  path: '/tattoo-studio-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioVisibilityReportRoute = StudioVisibilityReportRouteImport.update({
  id: '/studio-visibility-report',
  path: '/studio-visibility-report',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioGrowthCheckRoute = StudioGrowthCheckRouteImport.update({
  id: '/studio-growth-check',
  path: '/studio-growth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingBenchmarkRoute = PricingBenchmarkRouteImport.update({
  id: '/pricing-benchmark',
  path: '/pricing-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthModelRoute = GrowthModelRouteImport.update({
  id: '/growth-model',
  path: '/growth-model',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTattooPainChartRealityCheckRoute =
  ToolsTattooPainChartRealityCheckRouteImport.update({
    id: '/tools/tattoo-pain-chart-reality-check',
    path: '/tools/tattoo-pain-chart-reality-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OffersRoute,
} as any)
const GuidesGreyLineHealingWeekByWeekRoute =
  GuidesGreyLineHealingWeekByWeekRouteImport.update({
    id: '/guides/grey-line-healing-week-by-week',
    path: '/guides/grey-line-healing-week-by-week',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFullSleeveCostUkRoute = GuidesFullSleeveCostUkRouteImport.update({
  id: '/guides/full-sleeve-cost-uk',
  path: '/guides/full-sleeve-cost-uk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DotLovableOauthConsentRoute = DotLovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/growth-model': typeof GrowthModelRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRouteWithChildren
  '/pricing-benchmark': typeof PricingBenchmarkRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/studio-growth-check': typeof StudioGrowthCheckRoute
  '/studio-visibility-report': typeof StudioVisibilityReportRoute
  '/support': typeof SupportRoute
  '/tattoo-studio-booking': typeof TattooStudioBookingRoute
  '/tattoo-studio-client-retention': typeof TattooStudioClientRetentionRoute
  '/tattoo-studio-growth': typeof TattooStudioGrowthRoute
  '/tattoo-studio-management': typeof TattooStudioManagementRoute
  '/tattoo-studio-marketing': typeof TattooStudioMarketingRoute
  '/tattoo-studio-revenue': typeof TattooStudioRevenueRoute
  '/tattoo-studio-seo': typeof TattooStudioSeoRoute
  '/tattoo-studio-software': typeof TattooStudioSoftwareRoute
  '/tattoo-studio-visibility-scorecard': typeof TattooStudioVisibilityScorecardRoute
  '/terms': typeof TermsRoute
  '/tools/tattoo-pain-chart-reality-check': typeof ToolsTattooPainChartRealityCheckRoute
  '/guides/grey-line-healing-week-by-week': typeof GuidesGreyLineHealingWeekByWeekRoute
  '/guides/full-sleeve-cost-uk': typeof GuidesFullSleeveCostUkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotLovableOauthConsentRoute
  '/offers/$slug': typeof OffersSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/growth-model': typeof GrowthModelRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRouteWithChildren
  '/pricing-benchmark': typeof PricingBenchmarkRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/studio-growth-check': typeof StudioGrowthCheckRoute
  '/studio-visibility-report': typeof StudioVisibilityReportRoute
  '/support': typeof SupportRoute
  '/tattoo-studio-booking': typeof TattooStudioBookingRoute
  '/tattoo-studio-client-retention': typeof TattooStudioClientRetentionRoute
  '/tattoo-studio-growth': typeof TattooStudioGrowthRoute
  '/tattoo-studio-management': typeof TattooStudioManagementRoute
  '/tattoo-studio-marketing': typeof TattooStudioMarketingRoute
  '/tattoo-studio-revenue': typeof TattooStudioRevenueRoute
  '/tattoo-studio-seo': typeof TattooStudioSeoRoute
  '/tattoo-studio-software': typeof TattooStudioSoftwareRoute
  '/tattoo-studio-visibility-scorecard': typeof TattooStudioVisibilityScorecardRoute
  '/terms': typeof TermsRoute
  '/tools/tattoo-pain-chart-reality-check': typeof ToolsTattooPainChartRealityCheckRoute
  '/guides/grey-line-healing-week-by-week': typeof GuidesGreyLineHealingWeekByWeekRoute
  '/guides/full-sleeve-cost-uk': typeof GuidesFullSleeveCostUkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotLovableOauthConsentRoute
  '/offers/$slug': typeof OffersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/growth-model': typeof GrowthModelRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRouteWithChildren
  '/pricing-benchmark': typeof PricingBenchmarkRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/studio-growth-check': typeof StudioGrowthCheckRoute
  '/studio-visibility-report': typeof StudioVisibilityReportRoute
  '/support': typeof SupportRoute
  '/tattoo-studio-booking': typeof TattooStudioBookingRoute
  '/tattoo-studio-client-retention': typeof TattooStudioClientRetentionRoute
  '/tattoo-studio-growth': typeof TattooStudioGrowthRoute
  '/tattoo-studio-management': typeof TattooStudioManagementRoute
  '/tattoo-studio-marketing': typeof TattooStudioMarketingRoute
  '/tattoo-studio-revenue': typeof TattooStudioRevenueRoute
  '/tattoo-studio-seo': typeof TattooStudioSeoRoute
  '/tattoo-studio-software': typeof TattooStudioSoftwareRoute
  '/tattoo-studio-visibility-scorecard': typeof TattooStudioVisibilityScorecardRoute
  '/terms': typeof TermsRoute
  '/tools/tattoo-pain-chart-reality-check': typeof ToolsTattooPainChartRealityCheckRoute
  '/guides/grey-line-healing-week-by-week': typeof GuidesGreyLineHealingWeekByWeekRoute
  '/guides/full-sleeve-cost-uk': typeof GuidesFullSleeveCostUkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/.lovable/oauth/consent': typeof DotLovableOauthConsentRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/growth-model'
    | '/mcp'
    | '/offers'
    | '/pricing-benchmark'
    | '/privacy'
    | '/resources'
    | '/solutions'
    | '/studio-growth-check'
    | '/studio-visibility-report'
    | '/support'
    | '/tattoo-studio-booking'
    | '/tattoo-studio-client-retention'
    | '/tattoo-studio-growth'
    | '/tattoo-studio-management'
    | '/tattoo-studio-marketing'
    | '/tattoo-studio-revenue'
    | '/tattoo-studio-seo'
    | '/tattoo-studio-software'
    | '/tattoo-studio-visibility-scorecard'
    | '/terms'
    | '/tools/tattoo-pain-chart-reality-check'
    | '/guides/grey-line-healing-week-by-week'
    | '/guides/full-sleeve-cost-uk'
    | '/auth/callback'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/offers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/growth-model'
    | '/mcp'
    | '/offers'
    | '/pricing-benchmark'
    | '/privacy'
    | '/resources'
    | '/solutions'
    | '/studio-growth-check'
    | '/studio-visibility-report'
    | '/support'
    | '/tattoo-studio-booking'
    | '/tattoo-studio-client-retention'
    | '/tattoo-studio-growth'
    | '/tattoo-studio-management'
    | '/tattoo-studio-marketing'
    | '/tattoo-studio-revenue'
    | '/tattoo-studio-seo'
    | '/tattoo-studio-software'
    | '/tattoo-studio-visibility-scorecard'
    | '/terms'
    | '/tools/tattoo-pain-chart-reality-check'
    | '/guides/grey-line-healing-week-by-week'
    | '/guides/full-sleeve-cost-uk'
    | '/auth/callback'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/offers/$slug'
  id:
    | '__root__'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/growth-model'
    | '/mcp'
    | '/offers'
    | '/pricing-benchmark'
    | '/privacy'
    | '/resources'
    | '/solutions'
    | '/studio-growth-check'
    | '/studio-visibility-report'
    | '/support'
    | '/tattoo-studio-booking'
    | '/tattoo-studio-client-retention'
    | '/tattoo-studio-growth'
    | '/tattoo-studio-management'
    | '/tattoo-studio-marketing'
    | '/tattoo-studio-revenue'
    | '/tattoo-studio-seo'
    | '/tattoo-studio-software'
    | '/tattoo-studio-visibility-scorecard'
    | '/terms'
    | '/tools/tattoo-pain-chart-reality-check'
    | '/guides/grey-line-healing-week-by-week'
    | '/guides/full-sleeve-cost-uk'
    | '/auth/callback'
    | '/_authenticated'
    | '/.lovable/oauth/consent'
    | '/offers/$slug'
    | '/_authenticated/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  GrowthModelRoute: typeof GrowthModelRoute
  McpRoute: typeof McpRoute
  OffersRoute: typeof OffersRouteWithChildren
  PricingBenchmarkRoute: typeof PricingBenchmarkRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRoute
  StudioGrowthCheckRoute: typeof StudioGrowthCheckRoute
  StudioVisibilityReportRoute: typeof StudioVisibilityReportRoute
  SupportRoute: typeof SupportRoute
  TattooStudioBookingRoute: typeof TattooStudioBookingRoute
  TattooStudioClientRetentionRoute: typeof TattooStudioClientRetentionRoute
  TattooStudioGrowthRoute: typeof TattooStudioGrowthRoute
  TattooStudioManagementRoute: typeof TattooStudioManagementRoute
  TattooStudioMarketingRoute: typeof TattooStudioMarketingRoute
  TattooStudioRevenueRoute: typeof TattooStudioRevenueRoute
  TattooStudioSeoRoute: typeof TattooStudioSeoRoute
  TattooStudioSoftwareRoute: typeof TattooStudioSoftwareRoute
  TattooStudioVisibilityScorecardRoute: typeof TattooStudioVisibilityScorecardRoute
  TermsRoute: typeof TermsRoute
  ToolsTattooPainChartRealityCheckRoute: typeof ToolsTattooPainChartRealityCheckRoute
  GuidesGreyLineHealingWeekByWeekRoute: typeof GuidesGreyLineHealingWeekByWeekRoute
  GuidesFullSleeveCostUkRoute: typeof GuidesFullSleeveCostUkRoute
  DotLovableOauthConsentRoute: typeof DotLovableOauthConsentRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-model': {
      id: '/growth-model'
      path: '/growth-model'
      fullPath: '/growth-model'
      preLoaderRoute: typeof GrowthModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-benchmark': {
      id: '/pricing-benchmark'
      path: '/pricing-benchmark'
      fullPath: '/pricing-benchmark'
      preLoaderRoute: typeof PricingBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-growth-check': {
      id: '/studio-growth-check'
      path: '/studio-growth-check'
      fullPath: '/studio-growth-check'
      preLoaderRoute: typeof StudioGrowthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-visibility-report': {
      id: '/studio-visibility-report'
      path: '/studio-visibility-report'
      fullPath: '/studio-visibility-report'
      preLoaderRoute: typeof StudioVisibilityReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-booking': {
      id: '/tattoo-studio-booking'
      path: '/tattoo-studio-booking'
      fullPath: '/tattoo-studio-booking'
      preLoaderRoute: typeof TattooStudioBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-client-retention': {
      id: '/tattoo-studio-client-retention'
      path: '/tattoo-studio-client-retention'
      fullPath: '/tattoo-studio-client-retention'
      preLoaderRoute: typeof TattooStudioClientRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-growth': {
      id: '/tattoo-studio-growth'
      path: '/tattoo-studio-growth'
      fullPath: '/tattoo-studio-growth'
      preLoaderRoute: typeof TattooStudioGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-management': {
      id: '/tattoo-studio-management'
      path: '/tattoo-studio-management'
      fullPath: '/tattoo-studio-management'
      preLoaderRoute: typeof TattooStudioManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-marketing': {
      id: '/tattoo-studio-marketing'
      path: '/tattoo-studio-marketing'
      fullPath: '/tattoo-studio-marketing'
      preLoaderRoute: typeof TattooStudioMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-revenue': {
      id: '/tattoo-studio-revenue'
      path: '/tattoo-studio-revenue'
      fullPath: '/tattoo-studio-revenue'
      preLoaderRoute: typeof TattooStudioRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-seo': {
      id: '/tattoo-studio-seo'
      path: '/tattoo-studio-seo'
      fullPath: '/tattoo-studio-seo'
      preLoaderRoute: typeof TattooStudioSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-software': {
      id: '/tattoo-studio-software'
      path: '/tattoo-studio-software'
      fullPath: '/tattoo-studio-software'
      preLoaderRoute: typeof TattooStudioSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-visibility-scorecard': {
      id: '/tattoo-studio-visibility-scorecard'
      path: '/tattoo-studio-visibility-scorecard'
      fullPath: '/tattoo-studio-visibility-scorecard'
      preLoaderRoute: typeof TattooStudioVisibilityScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tattoo-pain-chart-reality-check': {
      id: '/tools/tattoo-pain-chart-reality-check'
      path: '/tools/tattoo-pain-chart-reality-check'
      fullPath: '/tools/tattoo-pain-chart-reality-check'
      preLoaderRoute: typeof ToolsTattooPainChartRealityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof OffersRoute
    }
    '/guides/grey-line-healing-week-by-week': {
      id: '/guides/grey-line-healing-week-by-week'
      path: '/guides/grey-line-healing-week-by-week'
      fullPath: '/guides/grey-line-healing-week-by-week'
      preLoaderRoute: typeof GuidesGreyLineHealingWeekByWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/full-sleeve-cost-uk': {
      id: '/guides/full-sleeve-cost-uk'
      path: '/guides/full-sleeve-cost-uk'
      fullPath: '/guides/full-sleeve-cost-uk'
      preLoaderRoute: typeof GuidesFullSleeveCostUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotLovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OffersRouteChildren {
  OffersSlugRoute: typeof OffersSlugRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersSlugRoute: OffersSlugRoute,
}

const OffersRouteWithChildren = OffersRoute._addFileChildren(OffersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  GrowthModelRoute: GrowthModelRoute,
  McpRoute: McpRoute,
  OffersRoute: OffersRouteWithChildren,
  PricingBenchmarkRoute: PricingBenchmarkRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRoute,
  StudioGrowthCheckRoute: StudioGrowthCheckRoute,
  StudioVisibilityReportRoute: StudioVisibilityReportRoute,
  SupportRoute: SupportRoute,
  TattooStudioBookingRoute: TattooStudioBookingRoute,
  TattooStudioClientRetentionRoute: TattooStudioClientRetentionRoute,
  TattooStudioGrowthRoute: TattooStudioGrowthRoute,
  TattooStudioManagementRoute: TattooStudioManagementRoute,
  TattooStudioMarketingRoute: TattooStudioMarketingRoute,
  TattooStudioRevenueRoute: TattooStudioRevenueRoute,
  TattooStudioSeoRoute: TattooStudioSeoRoute,
  TattooStudioSoftwareRoute: TattooStudioSoftwareRoute,
  TattooStudioVisibilityScorecardRoute: TattooStudioVisibilityScorecardRoute,
  TermsRoute: TermsRoute,
  ToolsTattooPainChartRealityCheckRoute: ToolsTattooPainChartRealityCheckRoute,
  GuidesGreyLineHealingWeekByWeekRoute: GuidesGreyLineHealingWeekByWeekRoute,
  GuidesFullSleeveCostUkRoute: GuidesFullSleeveCostUkRoute,
  DotLovableOauthConsentRoute: DotLovableOauthConsentRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
