/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TattooStudioVisibilityScorecardRouteImport } from './routes/tattoo-studio-visibility-scorecard'
import { Route as TattooStudioSoftwareRouteImport } from './routes/tattoo-studio-software'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudioGrowthCheckRouteImport } from './routes/studio-growth-check'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GrowthModelRouteImport } from './routes/growth-model'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsTattooPainChartRealityCheckRouteImport } from './routes/tools.tattoo-pain-chart-reality-check'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as GuidesGreyLineHealingWeekByWeekRouteImport } from './routes/guides.grey-line-healing-week-by-week'
import { Route as GuidesFullSleeveCostUkRouteImport } from './routes/guides.full-sleeve-cost-uk'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TattooStudioVisibilityScorecardRoute =
  TattooStudioVisibilityScorecardRouteImport.update({
    id: '/tattoo-studio-visibility-scorecard',
    path: '/tattoo-studio-visibility-scorecard',
    getParentRoute: () => rootRouteImport,
  } as any)
const TattooStudioSoftwareRoute = TattooStudioSoftwareRouteImport.update({
  id: '/tattoo-studio-software',
  path: '/tattoo-studio-software',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioGrowthCheckRoute = StudioGrowthCheckRouteImport.update({
  id: '/studio-growth-check',
  path: '/studio-growth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthModelRoute = GrowthModelRouteImport.update({
  id: '/growth-model',
  path: '/growth-model',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTattooPainChartRealityCheckRoute =
  ToolsTattooPainChartRealityCheckRouteImport.update({
    id: '/tools/tattoo-pain-chart-reality-check',
    path: '/tools/tattoo-pain-chart-reality-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OffersRoute,
} as any)
const GuidesGreyLineHealingWeekByWeekRoute =
  GuidesGreyLineHealingWeekByWeekRouteImport.update({
    id: '/guides/grey-line-healing-week-by-week',
    path: '/guides/grey-line-healing-week-by-week',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFullSleeveCostUkRoute = GuidesFullSleeveCostUkRouteImport.update({
  id: '/guides/full-sleeve-cost-uk',
  path: '/guides/full-sleeve-cost-uk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/growth-model': typeof GrowthModelRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/studio-growth-check': typeof StudioGrowthCheckRoute
  '/support': typeof SupportRoute
  '/tattoo-studio-software': typeof TattooStudioSoftwareRoute
  '/tattoo-studio-visibility-scorecard': typeof TattooStudioVisibilityScorecardRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/full-sleeve-cost-uk': typeof GuidesFullSleeveCostUkRoute
  '/guides/grey-line-healing-week-by-week': typeof GuidesGreyLineHealingWeekByWeekRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/tools/tattoo-pain-chart-reality-check': typeof ToolsTattooPainChartRealityCheckRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/growth-model': typeof GrowthModelRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/studio-growth-check': typeof StudioGrowthCheckRoute
  '/support': typeof SupportRoute
  '/tattoo-studio-software': typeof TattooStudioSoftwareRoute
  '/tattoo-studio-visibility-scorecard': typeof TattooStudioVisibilityScorecardRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/full-sleeve-cost-uk': typeof GuidesFullSleeveCostUkRoute
  '/guides/grey-line-healing-week-by-week': typeof GuidesGreyLineHealingWeekByWeekRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/tools/tattoo-pain-chart-reality-check': typeof ToolsTattooPainChartRealityCheckRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/growth-model': typeof GrowthModelRoute
  '/mcp': typeof McpRoute
  '/offers': typeof OffersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/studio-growth-check': typeof StudioGrowthCheckRoute
  '/support': typeof SupportRoute
  '/tattoo-studio-software': typeof TattooStudioSoftwareRoute
  '/tattoo-studio-visibility-scorecard': typeof TattooStudioVisibilityScorecardRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/full-sleeve-cost-uk': typeof GuidesFullSleeveCostUkRoute
  '/guides/grey-line-healing-week-by-week': typeof GuidesGreyLineHealingWeekByWeekRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/tools/tattoo-pain-chart-reality-check': typeof ToolsTattooPainChartRealityCheckRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/growth-model'
    | '/mcp'
    | '/offers'
    | '/privacy'
    | '/resources'
    | '/studio-growth-check'
    | '/support'
    | '/tattoo-studio-software'
    | '/tattoo-studio-visibility-scorecard'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/auth/callback'
    | '/guides/full-sleeve-cost-uk'
    | '/guides/grey-line-healing-week-by-week'
    | '/offers/$slug'
    | '/tools/tattoo-pain-chart-reality-check'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/growth-model'
    | '/mcp'
    | '/offers'
    | '/privacy'
    | '/resources'
    | '/studio-growth-check'
    | '/support'
    | '/tattoo-studio-software'
    | '/tattoo-studio-visibility-scorecard'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/auth/callback'
    | '/guides/full-sleeve-cost-uk'
    | '/guides/grey-line-healing-week-by-week'
    | '/offers/$slug'
    | '/tools/tattoo-pain-chart-reality-check'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/growth-model'
    | '/mcp'
    | '/offers'
    | '/privacy'
    | '/resources'
    | '/studio-growth-check'
    | '/support'
    | '/tattoo-studio-software'
    | '/tattoo-studio-visibility-scorecard'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/guides/full-sleeve-cost-uk'
    | '/guides/grey-line-healing-week-by-week'
    | '/offers/$slug'
    | '/tools/tattoo-pain-chart-reality-check'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  GrowthModelRoute: typeof GrowthModelRoute
  McpRoute: typeof McpRoute
  OffersRoute: typeof OffersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  StudioGrowthCheckRoute: typeof StudioGrowthCheckRoute
  SupportRoute: typeof SupportRoute
  TattooStudioSoftwareRoute: typeof TattooStudioSoftwareRoute
  TattooStudioVisibilityScorecardRoute: typeof TattooStudioVisibilityScorecardRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  GuidesFullSleeveCostUkRoute: typeof GuidesFullSleeveCostUkRoute
  GuidesGreyLineHealingWeekByWeekRoute: typeof GuidesGreyLineHealingWeekByWeekRoute
  ToolsTattooPainChartRealityCheckRoute: typeof ToolsTattooPainChartRealityCheckRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-visibility-scorecard': {
      id: '/tattoo-studio-visibility-scorecard'
      path: '/tattoo-studio-visibility-scorecard'
      fullPath: '/tattoo-studio-visibility-scorecard'
      preLoaderRoute: typeof TattooStudioVisibilityScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tattoo-studio-software': {
      id: '/tattoo-studio-software'
      path: '/tattoo-studio-software'
      fullPath: '/tattoo-studio-software'
      preLoaderRoute: typeof TattooStudioSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-growth-check': {
      id: '/studio-growth-check'
      path: '/studio-growth-check'
      fullPath: '/studio-growth-check'
      preLoaderRoute: typeof StudioGrowthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-model': {
      id: '/growth-model'
      path: '/growth-model'
      fullPath: '/growth-model'
      preLoaderRoute: typeof GrowthModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tattoo-pain-chart-reality-check': {
      id: '/tools/tattoo-pain-chart-reality-check'
      path: '/tools/tattoo-pain-chart-reality-check'
      fullPath: '/tools/tattoo-pain-chart-reality-check'
      preLoaderRoute: typeof ToolsTattooPainChartRealityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof OffersRoute
    }
    '/guides/grey-line-healing-week-by-week': {
      id: '/guides/grey-line-healing-week-by-week'
      path: '/guides/grey-line-healing-week-by-week'
      fullPath: '/guides/grey-line-healing-week-by-week'
      preLoaderRoute: typeof GuidesGreyLineHealingWeekByWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/full-sleeve-cost-uk': {
      id: '/guides/full-sleeve-cost-uk'
      path: '/guides/full-sleeve-cost-uk'
      fullPath: '/guides/full-sleeve-cost-uk'
      preLoaderRoute: typeof GuidesFullSleeveCostUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OffersRouteChildren {
  OffersSlugRoute: typeof OffersSlugRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersSlugRoute: OffersSlugRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  GrowthModelRoute: GrowthModelRoute,
  McpRoute: McpRoute,
  OffersRoute: OffersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  StudioGrowthCheckRoute: StudioGrowthCheckRoute,
  SupportRoute: SupportRoute,
  TattooStudioSoftwareRoute: TattooStudioSoftwareRoute,
  TattooStudioVisibilityScorecardRoute: TattooStudioVisibilityScorecardRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  GuidesFullSleeveCostUkRoute: GuidesFullSleeveCostUkRoute,
  GuidesGreyLineHealingWeekByWeekRoute: GuidesGreyLineHealingWeekByWeekRoute,
  ToolsTattooPainChartRealityCheckRoute: ToolsTattooPainChartRealityCheckRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
