// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { resolveSupabaseConfig } from './config.mjs';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    // The public report RPC must never leave the UI in an indefinite
    // "Preparing your report" state if the database call stalls.
    const requestUrl =
      typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.href
          : input.url;
    if (requestUrl.includes('/rest/v1/rpc/publish_visibility_report')) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 15000);
      const signal = init?.signal ?? controller.signal;
      return fetch(input, { ...init, headers, signal }).finally(() => clearTimeout(timeout));
    }

    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Prefer deployment-scoped environment values. If the public Vite variables are
  // absent, fall back to the canonical INKSIGHTS public project configuration.
  // The publishable key is browser-safe; privileged credentials remain server-only.
  const processEnv = typeof process !== 'undefined' ? process.env : undefined;
  const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseConfig(
    import.meta.env,
    processEnv,
  );

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});