// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { resolveSupabaseConfig } from './config.mjs';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function safeJsonParse(value: BodyInit | null | undefined): Record<string, unknown> | null {
  if (typeof value !== 'string') return null;
  try {
    const parsed = JSON.parse(value);
    return parsed && typeof parsed === 'object' ? parsed as Record<string, unknown> : null;
  } catch {
    return null;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    const requestUrl =
      typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.href
          : input.url;

    // Security boundary: keep the public report token in the same-origin app route.
    // The browser-facing Supabase RPC call is transparently proxied so the database
    // function can be restricted to service_role after this route is deployed.
    if (
      typeof window !== 'undefined' &&
      requestUrl.includes('/rest/v1/rpc/publish_visibility_report')
    ) {
      const payload = safeJsonParse(init?.body);
      const reportId = payload?.['p_report_id'];
      const publicToken = payload?.['p_public_token'];

      if (typeof reportId === 'string' && typeof publicToken === 'string') {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 15000);
        const signal = init?.signal ?? controller.signal;
        const target = `/api/public/visibility-report?reportId=${encodeURIComponent(reportId)}&token=${encodeURIComponent(publicToken)}`;

        return fetch(target, {
          method: 'GET',
          headers: { Accept: 'application/json' },
          signal,
          credentials: 'same-origin',
        }).finally(() => clearTimeout(timeout));
      }
    }

    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Prefer deployment-scoped environment values. If a Vercel Preview is missing
  // them, fall back to the canonical INKSIGHTS public project configuration.
  // The publishable key is intentionally browser-safe; service-role credentials
  // remain server-only and are never included here.
  const processEnv = typeof process !== 'undefined' ? process.env : undefined;
  const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseConfig(
    import.meta.env,
    processEnv,
  );

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});